### ISSUE TITLE
SCIM 2.0 support

### ISSUE THREAD

**Issue by pslestang** [ory/kratos#1028]
**Is your feature request related to a problem? Please describe.**

Feature is not related to a problem

**Describe the solution you'd like**

I would like Kratos implements SCIM 2.0 protocol
https://tools.ietf.org/html/rfc7642
https://tools.ietf.org/html/rfc7643
https://tools.ietf.org/html/rfc7644

**Describe alternatives you've considered**

Alternative is to use an other software

**Additional context**

NA

**Comment by aeneasr** [comment]
If the feature is not related to a problem, why do you need it? Maybe you could explain a bit more why you need SCIM. We're generally open to have it implemented but lack resources to do so as there are other, more important things such as 2FA/MFA, Ory Hydra integration, and more.

We do however appreciate contributions if you're up to the challenge!

**Comment by pslestang** [comment]
I mean by it's not related to a problem that I do not face an issue with the current code (understand a bug in the code), I'd just like to get SCIM protocol implemented mainly because it is a standard with a standard REST API and that I prefer use standards instead of relying on custom implementation.
I do note for the contributions and will contribute if possible!

**Comment by aeneasr** [comment]
Awesome! If you plan on working on this we should synch up so that we can reduce the amount of work you have to do!

Generally, Ory Kratos implements the things needed for SCIM such as custom identity schemas (called SCIM schemas in SCIM). I think the first priority when implementing SCIM support would be to identify areas which are currently not SCIM compatible (I don't think there are any to be honest!) and lay out a plan how Ory Kratos data would be made SCIM compatible.

**Comment by abujagonda** [comment]
What is the current status of SCIM 2.0 support in Ory Kratos?

**Comment by rafaelvannucci** [comment]
Hi team!

Having SCIM is a game changer for us (considering we become an Ory customer in the future).

Okta understood the business value in provide provisioning/deprovisioning capabilities in their integration network. SCIM offer a grateful ROA because is scalable, as most of enterprise customers doesn't have time, resources etc to manage a giant number of SaaS applications lifecycle (ie. Slack, Google, and more 5,000 apps...)

**Comment by aeneasr** [comment]
@smoyer64 thank you so much for the kind words, sounds like quite the journey :) While we don't have roles specifically for SCIM (there are currently mor epressing priorities) we always look for opportunities wherever they arise! If you're interested to work on SCIM at Ory, please do apply (e.g. for full stack) :)

**Comment by alexrollin** [comment]
Is there any update on SCIM support?

**Comment by c0depwn** [comment]
Just checking in what the progress is on this. Are there still any plans to implement a SCIM implementation in kratos? 

It might be interesting to have a SCIM implementation to support quick provisioning and de-provisioning of users specifically for enterprise-like customers which manage their users through systems such as Microsoft Entra/AD.

**Comment by c0depwn** [comment]
@aeneasr Awesome! Thank you for the swift answer, I was not sure about the self-hosting support for SCIM.
