### ISSUE TITLE
Quickstart doesn't work

### ISSUE THREAD

**Issue by perevezencev** [ory/kratos#1114]
**Describe the bug**

An error occurs when launching the Quick Start Guide

**Reproducing the bug**

1. Clone repo
2. Run `docker-compose -f ./quickstart.yml -f ./quickstart-postgres.yml up --build`
3. `unknown flag: --watch-courier`

_Server logs_

```
kratos_1                      | Error: unknown flag: --watch-courier
kratos_1                      | Usage:
kratos_1                      |   kratos serve [flags]
kratos_1                      | 
kratos_1                      | Flags:
kratos_1                      |       --dev                 Disables critical security features to make development easier
kratos_1                      |       --disable-telemetry   Disable anonymized telemetry reports - for more information please visit https://www.ory.sh/docs/ecosystem/sqa
kratos_1                      |   -h, --help                help for serve
kratos_1                      | 
kratos_1                      | Global Flags:
kratos_1                      |   -c, --config string   Path to config file. Supports .json, .yaml, .yml, .toml. Default is "$HOME/.kratos.(yaml|yml|toml|json)"
kratos_1                      | 
kratos_1                      | unknown flag: --watch-courier
```

**Comment by vinckr** [comment]
Can you provide some more info on what you were trying to do? 
You dont need `--watch-courier` for the quickstart. 

Also, while we are an international community, we speak and use english  🙂

**Comment by vinckr** [comment]
Also please use Github Discussions or our Slack (ory.sh/chat) for support and questions.
Closing for now, feel free to respond with more details or start a discussion in the Slack.

**Comment by perevezencev** [comment]
> Can you provide some more info on what you were trying to do?
> You dont need `--watch-courier` for the quickstart.
> 
> Also, while we are an international community, we speak and use english 🙂

Sorry for my mistake.
I am just clone repo and run `docker-compose -f ./quickstart.yml -f ./quickstart-postgres.yml up --build`

**Comment by vinckr** [comment]
I see, I will look into it later, thanks for your report!

**Comment by vinckr** [comment]
Hey there seems to be a problem with the flag! 
It is included into the quickstart.yml at the moment so that is why the quickstart fails. 

For a quick fix: 

Go to: 
https://github.com/ory/kratos/blob/master/quickstart.yml
Go to line 41:
`command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier`
remove the `--watch-courier` flag and save. 

Now your quickstart should be working @perevezencev . 
I will look into why the flag was failing.

**Comment by vinckr** [comment]
@zepatrik 
How does `--watch-courier` work or is it buggy?

Quickstart is broken at the moment due to:
`unknown flag: --watch-courier`

**Comment by zepatrik** [comment]
The change was introduced by https://github.com/ory/kratos/pull/1062

But this is not yet released. Please follow the [quickstart](https://www.ory.sh/kratos/docs/quickstart) closely. It says
```
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.5.5-alpha.1
```
You clearly forgot the checkout step, otherwise the unreleased changes would not have been in your working tree.
