### ISSUE TITLE
Support JSON Response for Browser Flows

### ISSUE THREAD

**Issue by borchero** [ory/kratos#1138]
**Is your feature request related to a problem? Please describe.**

When implementing an SPA, it is preferable to not reload the page when initiating the login/registration flow. However, ORY Kratos does not easily allow for any behavior besides redirecting. An alternative would be the API endpoint, but it does not supply a CSRF token.

**Describe the solution you'd like**

Browser flows should allow returning JSON just like the API flows. This could easily be achieved by setting the `Accept: application/json` header whenever the browser prefers a JSON response over a redirect. The CSRF token can easily be supplied by setting the `Set-Cookie` header on the JSON response.

**Describe alternatives you've considered**

Currently, I'm setting the redirect URL for login/registration to point at my own JSON API, basically echoing the redirect parameters (i.e. the flow ID). Surely, this setup introduces an additional point of failure and is nothing but redundant.

**Comment by aeneasr** [comment]
This is on the roadmap for 0.6

**Comment by sbussard** [comment]
@hasura made a guide on storing jwts, and @benawad made a brief video overview of that article here https://www.youtube.com/watch?v=iD49_NIQ-R4

I made a reference implementation here 
https://github.com/sbussard/jwt-reference-implementation

A week or two ago I started investigating a third party alternative to writing my own authentication system, to leverage feature such a mfa and email verification. After iterating through some solutions I arrived at @ory Kratos.

At this time it seems that Kratos is not quite ready for handling SPAs on its own, due to lack of refresh tokens

Please correct me if this is wrong.

The two approaches that make sense to me are 
(1) to implement a refresh-token flow in the Kratos api
or if that proves difficult, to 
(2) create a spa-adapter api layer to handle interactions with SPAs

My preference is the first option.

**Comment by aeneasr** [comment]
Refresh tokens are an OAuth2 terminology and have nothing to do with SPAs. There is a common theme that people think they need OAuth2 but it is completely wrong and misguided, feeded by the fuel of Auth0 and Okta who sell you complexity as standardization or secrutiy. OAuth2, refresh tokens, all of that makes things wonky, hard to implement, and in the end harder to secure.

All an SPA needs is to talk to your server and get a response that is „authenticated“ or not.
Nothing else. Cookies are great for this, and Ory Kratos supports cookies very well. Cookies work for AJAX natively without hassle.

My recent PR (https://github.com/ory/kratos/pull/1367) will also improve the way SPAs invoke the SDK so hopefully these concepts will slowly fall into oblivion when people realize that login and OAuth2 are not the same :)

https://www.ory.sh/hydra/docs/concepts/before-oauth2/

**Comment by aeneasr** [comment]
That sounded probably a bit too defensive ;) Just get‘s frustrating to see people fall into the same trap laid by sales monsters over and over again.

By the way, here’s an example app implemented by a community member for Kratos 0.5 and react/SPA: https://github.com/ory/kratos-selfservice-ui-react/pull/2

**Comment by sbussard** [comment]
@philharvey would like this response
