### ISSUE TITLE
recovery link is open by email app

### ISSUE THREAD

**Issue by samvandenberghe** [ory/kratos#1142]
Certain email apps (like office outlook) use link preview, Which visits the link and "uses" the token so by the time the user tries to recover the account the token is invalid.

Either account recovery is specifically for setting passwords instead temporary login.

The current work-around we are investigating is delaying the request to kratos until there is user interaction (clicking a link). which would remove the security of invalidating the token on request. But the problem is a blocking issue for us.

**Comment by aeneasr** [comment]
Ahh, outlook - don't we all love it?

I don't know how to approach this best at the moment. We could maybe add a short grace period to the recovery link?

**Comment by samvandenberghe** [comment]
I found some post detailing similar issues. outlook does have a specific user-agent but that doesn't appear as a scalable solution.

**Comment by williamohara** [comment]
Interesting problem. I'm actually about to start coding my recovery flow. Perhaps don't expire the token until the password is actually changed or after configurable time period - which ever comes first.

**Comment by aeneasr** [comment]
Yeah I agree, I think we can add a short "grace period" to allow e.g. a couple of seconds to pass between preview and clicking of the link.

**Comment by samvandenberghe** [comment]
I'm not sure if a couple of seconds grace period is enough. Our users mentioned that their mail server has quite overzealous phishing/spam filters. So we expect quite a bit of time between the first request and then the actual user request.

**Comment by aeneasr** [comment]
And we can not rely on the user agent, correct? Is there maybe a header or something else we could use? How are others approaching this?

**Comment by samvandenberghe** [comment]
Useragent could work in this specific case, but might not work for other clients or plugins.

I had found:
https://stackoverflow.com/questions/43443947/how-to-stop-e-mail-clients-from-visiting-links-in-e-mail-automatically
https://stackoverflow.com/questions/34346732/do-any-common-email-clients-pre-fetch-links-rather-than-images
https://security.stackexchange.com/questions/211258/do-mail-servers-follow-links-in-emails-as-part-of-a-security-scan-before-inbox-d

**Comment by BengtHagemeister** [comment]
Magic login links (like https://magic.link or https://vercel.com) have a similar problem, as it would be a severe security issue when email clients would automatically verify a login request. I unfortunately do not really know how they solved this, but it might be smart to explore into this direction as they must have a very stable solution for this problem.

**Comment by zepatrik** [comment]
Adding a form/button that requires user interaction is what I have seen in the wild, and what looks like a stable solution.

**Comment by aeneasr** [comment]
A form/button to the email?

**Comment by zepatrik** [comment]
A form on the side where you land on. So Kratos requires a `POST`/... of some value encoded in the URL basically. This can then be solved in the UI however people wish.

**Comment by aeneasr** [comment]
Thank you @BengtHagemeister - could you maybe take a look at their implementation and share your results? We can then think how to implement this best in Ory Kratos.

**Comment by aeneasr** [comment]
I thought about this a bit more - I think it is ok to bind the recovery flow to a specific browser. Meaning that we'll set up a cookie when recovery is being started (for browser flows) and check if the cookie exists when the user clicks the recovery link. This means that we bind the recovery process to a specific browser and device which could be annoying when you try to recover the account on another device (as it won't work) but in the context of security it does make sense IMO to bind the process to exactly one device.

Unfortunately this won't work with recovery via API flows.

Other websites deal with this by asking you to update your password before you get your session back via the log in flow. The problem in Kratos is that you don't always have a password but instead - for example - a TOTP or social sign in, which is why we show you the settings screen after authentication.

**Comment by zepatrik** [comment]
So it would not work on a different device but the link is not invalidated? That would be acceptable from a UX perspective I guess. I experienced some bad UX with pages where I did not use my default browser and it would open in the default one, the link was then invalidated.
Don't know if it is good from a security standpoint though.

**Comment by BengtHagemeister** [comment]
> Thank you @BengtHagemeister - could you maybe take a look at their implementation and share your results? We can then think how to implement this best in Ory Kratos.

I have looked into this and it seems that they use some kind of bot detection. If they think that a bot is visiting the page, they are prompting the user to click a "yes this is me" button. I don't think that implementing a bot system is the way to go.

> I thought about this a bit more - I think it is ok to bind the recovery flow to a specific browser. Meaning that we'll set up a cookie when recovery is being started (for browser flows) and check if the cookie exists when the user clicks the recovery link. This means that we bind the recovery process to a specific browser and device which could be annoying when you try to recover the account on another device (as it won't work) but in the context of security it does make sense IMO to bind the process to exactly one device.
> 
> Unfortunately this won't work with recovery via API flows.
> 
> Other websites deal with this by asking you to update your password before you get your session back via the log in flow. The problem in Kratos is that you don't always have a password but instead - for example - a TOTP or social sign in, which is why we show you the settings screen after authentication.

I do not really like the idea with allowing users to only sign in with the browser they started the initial request with. Auth0 has something similar implemented for their passwordless auth and people "hate" it (https://community.auth0.com/t/passwordless-email-magic-link-must-be-opened-in-same-browser/11404). 

But maybe a combination: If a user has the cookie set he is silently redirected without any interference, otherwise he will be asked to perform some kind of captcha (might be as easy as pressing a button). Establishing this as an internal component would allow to also use it for potential passwordless logins etc.

**Comment by jezell** [comment]
Not working from another device would definitely be terrible. In many cases people start the flow in a browser but then open these links on their phone because it's easier to get access to email there for whatever reason.

What about an approach using six digit codes like two factor auth over text generally works. In this approach, after requesting an email link, the screen would immediately update to say "enter the 6 digit code we sent you in email". At this point, the user has a few different paths they might take:

1) They open their email on any device and then get the six digit code and type it in. They continue in the current browser window which allows the flow to proceed. This is nice because even if you look at the email on another device, you don't have to continue on the other device.

2) They click the link in email on a different device, they get the same UI prompting to enter a six digit code and then continue from there.

3) They click the email from the same device. In this case a few things could happen, either the UI to enter the code is presented when the email client opens a new window, or because they are on the same device cookies or local storage could be used to allow the user to proceed automatically from the link without manually entering the code which kind of gives you the best of both worlds. Fast entry if you are on the same device, but a way to proceed that isn't so painful when you aren't.

**Comment by radekg** [comment]
Why not to allow modifying the link embedded in the email such that it becomes possible to implement an intermediate stage, say a button to click?

**Comment by aeneasr** [comment]
I think we'll go with the code solution in the end. It is more stable and doesn't have the issues described in this issue. We already have the flow's UIs so it should be rather straight forward to be added.

**Comment by aeneasr** [comment]
Follow up: https://github.com/ory/kratos/issues/1451

**Comment by aeneasr** [comment]
As we are planning to deprecate this strategy, and move on to #1451, I will be closing this as there is a follow up available.
