### ISSUE TITLE
Email verification link is automatically opened by mail provider

### ISSUE THREAD

**Issue by BengtHagemeister** [ory/kratos#1202]
This is the same problem as described in #1142 but with verification links.

When registering a new user the email verification link is automatically clicked by the email provider. This leads to an automatic verification of the users email. This could be potentially exploited.

This was reproduced with Office 365.

Solutions could be:
- user interaction before verifying the email (clicking a button).
- ~~user needs to login before the email is verified.~~

**Comment by aeneasr** [comment]
So login is not required to verify an email because sometimes you are not allowed to sign in before the mail is verified. It should however not auto-verify!

**Comment by aeneasr** [comment]
Follow up: https://github.com/ory/kratos/issues/1451

**Comment by mitar** [comment]
I think this is made even more problematic because default template for e-mail verification is very sparse:

```
Hi, please verify your account by clicking the following link: http://127.0.0.1:4433/self-service/verification?flow=d98b5e05-a51e-4caf-a097-8eec8cd6ea20&token=vX7PzARGFY0mymQnzPHSe6IABvl5SuAQ
```

It does not include much information. So people might try to just click on the link to learn more about what is this e-mail about. I think more text saying something like "if you do not recognize or have not expected this e-mail, it is safe to ignore it, or report it <here>". Moreover, e-mail should somewhere tell something about what is this account for, to remind the user. I think even default template should include text like this to help developers adopt similar language once they customize it.

**Comment by aeneasr** [comment]
The default strategy now uses `code` so this is considered to be solved.
