### ISSUE TITLE
Have Kratos optionally supply and verify CSRF tokens in API Flows

### ISSUE THREAD

**Issue by mattbonnell** [ory/kratos#1213]
**Is your feature request related to a problem? Please describe.**

We're exploring the potential for first-party applications to integrate with our central Kratos service while having the flexibility to implement their own UIs. Seems exposing the API flows to such trusted parties and letting them use them with their own forms would be the way to go. They would initiate an API flow, retrieve it, use the data to populate a form, have the form POST to their own backend, and then make an API call to Kratos complete the flow with the collected data. However, it would be nice if the API flows could (optionally) generate and verify a CSRF token that these parties could embed in their forms. This way, they wouldn't each need to implement a CSRF mechanism and we'd just need to ensure that they're properly handling the token during the above-described process (ie not doing something weird like storing the token server-side instead of having it POSTed in the form).

**Describe the solution you'd like**
- Add some `csrf_check=true` (just an example, bad name) parameter to the "Initialize X Flow for API clients" requests (eg [Login](https://www.ory.sh/kratos/docs/reference/api#initialize-login-flow-for-api-clients)), which causes a CSRF token to be included in the response
- Upon completion of this API flow (eg [Login](https://www.ory.sh/kratos/docs/reference/api#complete-login-flow-with-usernameemail-password-method)), if this `csrf_check` was given in the "Initialize" request, verify that the correct csrf token was returned.

**Describe alternatives you've considered**

Have each of the first-party clients implement their own CSRF mechanism. This would open up a lot more attack vectors, as the authentication mechanism will only be as strong as the weakest link. If Kratos manages this CSRF check, and none of the trusted parties are purposefully subverting it in their code, we can sleep a bit easier at night. 

**Additional context**

**Comment by mbonnell-wish** [comment]
We've decided not to take this approach. I'll leave this up in case there's a discussion to be had around this.

**Comment by aeneasr** [comment]
I don't think this can work - CSRF is a protection against browser doing things they shouldn't do, because browsers send cookies per default. Anti-CSRF tokens work like this:

- You set a csrf token seed and store that in a cookie
- You generate a token from the seed from the cookie and give that to the client
- You check if the token (in header, query, body) is from the same seed that is in the cookie

API clients do not send cookies unless explicitly implemented, so CSRF protection can not work as we can not verify the CSRF token. Therefore I am not sure how this could be implemented and if it would improve security.

I would therefore mark this as wontfix/close.
