### ISSUE TITLE
client api Whoami not work with Header `Authorization`

### ISSUE THREAD

**Issue by und3fined** [ory/kratos#1215]
Hi team,

Whoami not support query authorization, but code generate with query.
No any Header `Authorization` is set

Bug in here https://github.com/ory/kratos/blob/95b33768138352427d87b6e147698142b955c3b3/internal/httpclient/client/public/whoami_parameters.go#L156

Please hotfix it thanks.

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by und3fined** [comment]
**Describe the bug**

- I use client sdk: `Regenerate OpenAPI client v0.5.5-alpha.2`
- Kratos `v0.5.5-alpha.1`
- I don't know if it's kratos bug / kratos-client bug

In api `public.Whoami(params *WhoamiParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*WhoamiOK, error)`
It's not work with `Authorization` headers

If it's client bug then in here https://github.com/ory/kratos-client-go/blob/eac42ac8684469e5cf19a75b6ea374d0a6a267f8/client/public/whoami_parameters.go#L157

If it's kratos bug, bug in here: https://github.com/ory/kratos/blob/83aedcb885acb96c5deb39fff675d5f0528af32d/session/manager_http.go#L98

**Reproducing the bug**

- Bug from kratos/ kratos-client , you can see code for bug.

**Expected behavior**

I can get a valid session

**Comment by ycgambo** [comment]
I'm using go client, don't know if the above pull fixes that.

	github.com/ory/kratos-client-go v0.5.5-alpha.4
	github.com/ory/kratos v0.5.5-alpha.1

here's the source code in `kratos-client-go/client/public/whoami_parameters.go` 
```go
	if o.Authorization != nil {

		// query param Authorization
		var qrAuthorization string

		if o.Authorization != nil {
			qrAuthorization = *o.Authorization
		}
		qAuthorization := qrAuthorization
		if qAuthorization != "" {

			if err := r.SetQueryParam("Authorization", qAuthorization); err != nil {
				return err
			}
		}
	}
```

but query param is not used in `kratos/session/helper.go`
```go
func bearerTokenFromRequest(r *http.Request) (string, bool) {
	parts := strings.Split(r.Header.Get("Authorization"), " ")

	if len(parts) == 2 && strings.ToLower(parts[0]) == "bearer" {
		return parts[1], true
	}

	return "", false
}
```

**Comment by und3fined** [comment]
@aeneasr any release for this fix?
