### ISSUE TITLE
Can you add new provider vk.com?

### ISSUE THREAD

**Issue by 0x000777** [ory/kratos#1234]
Can you add new provider vk.com?

please see documentation: https://vk.com/dev/authcode_flow_user

**Comment by NickUfer** [comment]
I worked on the integration of vk some time ago. I think the problem for me was that you register with a phone number and not with an email which was a bit odd. I wanted to investigate if this can be problematic but I never got there because of other stuff I had to do.

If it is technically no problem to have a phone number instead of an email I can make a PR the next days.

**Comment by Highter87** [comment]
no, that's not a problem. It doesn't matter how you are registered (via phone or email).
authorization is a copy of facebook

**Comment by Highter87** [comment]
`package oidc

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"

	"github.com/pkg/errors"
	"golang.org/x/oauth2"

	"github.com/ory/herodot"
)

type ProviderVkontakte struct {
	*ProviderGenericOIDC
}

func NewProviderVkontakte(
	config *Configuration,
	public *url.URL,
) *ProviderVkontakte {
	config.IssuerURL = "https://vk.com"
	return &ProviderVkontakte{
		ProviderGenericOIDC: &ProviderGenericOIDC{
			config: config,
			public: public,
		},
	}
}

func (g *ProviderVkontakte) OAuth2(ctx context.Context) (*oauth2.Config, error) {
	p, err := g.provider(ctx)
	if err != nil {
		return nil, err
	}

	endpoint := p.Endpoint()

	if endpoint.AuthURL == "" {
		endpoint.AuthURL = "https://oauth.vk.com/authorize"
	}
	if endpoint.TokenURL == "" {
		endpoint.TokenURL = "https://oauth.vk.com/access_token"
	}

	return g.oauth2ConfigFromEndpoint(endpoint), nil
}

func (g *ProviderVkontakte) Claims(ctx context.Context, exchange *oauth2.Token) (*Claims, error) {
	o, err := g.OAuth2(ctx)
	if err != nil {
		return nil, errors.WithStack(herodot.ErrInternalServerError.WithReasonf("%s", err))
	}

	client := o.Client(ctx, exchange)

	u, err := url.Parse("https://api.vk.com/method/users.get?fields=photo_200&access_token=" + exchange.AccessToken + "&v=5.103")
	if err != nil {
		return nil, errors.WithStack(herodot.ErrInternalServerError.WithReasonf("%s", err))
	}

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, errors.WithStack(herodot.ErrInternalServerError.WithReasonf("%s", err))
	}

	resp, err := client.Do(req)
	if err != nil {
		return nil, errors.WithStack(herodot.ErrInternalServerError.WithReasonf("%s", err))
	}
	defer resp.Body.Close()

	var user struct {
		Id         string `json:"id,omitempty"`
		Name       string `json:"name,omitempty"`
		FirstName  string `json:"first_name,omitempty"`
		LastName   string `json:"last_name,omitempty"`
		MiddleName string `json:"middle_name,omitempty"`
		Email      string `json:"email,omitempty"`
		Picture    struct {
			Data struct {
				Url string `json:"photo_200,omitempty"`
			}
		}
		EmailVerified bool
		BirthDay      string `json:"birthday,omitempty"`
		Gender        string `json:"gender,omitempty"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&user); err != nil {
		return nil, errors.WithStack(herodot.ErrInternalServerError.WithReasonf("%s", err))
	}

	if user.Email != "" {
		user.EmailVerified = true
	}

	return &Claims{
		Issuer:            u.String(),
		Subject:           user.Id,
		Name:              user.Name,
		GivenName:         user.FirstName,
		FamilyName:        user.LastName,
		MiddleName:        user.MiddleName,
		Nickname:          user.Name,
		PreferredUsername: user.Name,
		Picture:           user.Picture.Data.Url,
		Email:             user.Email,
		EmailVerified:     user.EmailVerified,
		Gender:            user.Gender,
		Birthdate:         user.BirthDay,
	}, nil
}
`

**Comment by sash2222** [comment]
Hello @NickUfer, it seems that the Generic provider is not suitable for VK due to such trifles that VK does not have an endpoint /.well-known, and Kratos expects it when using the Geenric provider and does not accept certain endpoints in the configuration manually: issuer_url, auth_url, token_url ...
Earlier, @Highter87 posted his version here, could you accept it or make your own implementation.
As for the email field, this is not so critical for us, the main thing is that the authorization works.
We would be very grateful to you.

**Comment by aeneasr** [comment]
It's not really common to ask maintainers or community members to "do something". You can open requests and share ideas but this is not a free buffet. Doing things costs time and as you can imagine we don't have much time maintaining these projects.

The best option to implement what you want is to implement it and make a PR. An alternative is to help support the ecosystem on GitHub Sponsors, Patreon or OpenCollective (click the sponsor button on the top right of this page). But that still does not mean the feature is implemented - it just means that we can spend a little bit more time or maybe even hire someone to help out with things like this.

Also, please adhere to the issue template.

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by sash2222** [comment]
---
name: add VKONTAKTE OIDC provider.
about: The social network VKONTAKTE has a fairly large audience and many projects based on it. OAuth support would be great.
---

We will be corrected! But I didn't want to be respectful of the community. You are doing a great job!

**Describe the solution you'd like**

Apparently, Generic OIDC is not suitable for using VK because they have their own implementation in details, in particular, they do not have a standard / .well-know configuration distribution point for the protocol that Generic expects.
Judging by the code, we can use the FB provider as an example to create a provider for VK on its basis, registering the necessary endpoints and a method for receiving claims there.

**Describe alternatives you've considered**

Change Generic OIDC. Do not require the mandatory presence of ./well-know if endpoints are specified in the configuration.

**Additional context**

https://vk.com/dev.php?method=authcode_flow_user
[logs.txt](https://github.com/ory/kratos/files/6357142/logs.txt)
[Uierror.txt](https://github.com/ory/kratos/files/6357143/Uierror.txt)
