### ISSUE TITLE
X-Session-Token on whoami request

### ISSUE THREAD

**Issue by reliablestaking** [ory/kratos#1375]
**Describe the bug**

Setting the "X-Session-Token" header on the /sessions/whoami request always ressults in a 401, if I change it to "Cookie", it return correctly.

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by reliablestaking** [comment]
Running kratos in a  docker image on windows, have tried both `v0.6.2` and the `latest` tags

If I run a command like `curl -s -v -X GET -H "Accept: application/json" -H "Cookie: cookie_here" http://127.0.0.1:4433/sessions/whoami` the expected json is returned, but if I run `curl -s -v -X GET -H "Accept: application/json" -H "X-Session-Token: cookie_here" http://127.0.0.1:4433/sessions/whoami` I get

```
{"error":{"code":401,"status":"Unauthorized","reason":"No valid session cookie found.","message":"The request could not be authorized"}}
```

**Comment by aeneasr** [comment]
You need to send a session token, which you get using one of the API flows, when using the ‚X-Session-Token‘ header, not the cookie! The cookie is a cookie and needs to be sent in the cookie header :)

**Comment by reliablestaking** [comment]
Ok, I was using the auto generated go client, which expects an X-Session-Token, I didn't see any option for the Cookie using that client, which caused the confusion.
