### ISSUE TITLE
SMTP URL doesn't support `#` in password

### ISSUE THREAD

**Issue by bernardolk** [ory/kratos#1532]
**Describe the bug**

Whenever trying to use the email courier with a SMTP URL where the credentials (password) requires a hashtag, it won't work, possibly because of this line of code:
https://github.com/ory/kratos/blob/c21bb80a749df7b224a8ac3f15fa62523a78d805/driver/config/config.go#L709

**Reproducing the bug**

**Expected behavior**

For the code to parse correctly the password section of the SMTP URL and if it's not possible to have a particular character, emit an error message explaining that it encountered this problem.

**Environment**

- Version: v0.6.6
- Environment: Terraform + Helm Charts, k8s

**Comment by aeneasr** [comment]
Try the url encoded form `%23`

**Comment by bernardolk** [comment]
I've tried, but then google will give bad credentials.
Also, if my password has `%23` exactly, how would it differentiate between a `#` and literal `%23`? For the email part it makes all the sense since special characters are invalid.

**Comment by aeneasr** [comment]
You would supply url encoding, which encodes to `%` to `%25 so you would end up with `%2523`. Please read more about urlencoding: https://www.w3schools.com/tags/ref_urlencode.ASP

Someone else had a similar problem and there the encoding worked: https://github.com/ory/kratos/discussions/1539#discussioncomment-1042013

It's also a bit confusing that urlencoding it doesn't work, as it would skip the linked code

https://github.com/ory/kratos/blob/c21bb80a749df7b224a8ac3f15fa62523a78d805/driver/config/config.go#L709

because `%23` would be converted to `#` later.

I wouldn't supply your password to this website, but you should try to url encode the password using https://www.urlencoder.org

Maybe you have made a typo by mistake which caused the urlencoded password to fail.

**Comment by aeneasr** [comment]
The best way to prove your suspicion would be to add a failing test case to https://github.com/Zippersk/kratos/blob/master/driver/config/config_test.go which proves that hashtags in passwords (urlencoded) do not work - then we can supply a fix :)

**Comment by bernardolk** [comment]
@aeneasr thanks for the reply. I will have to replace the SMTP configurations soon, so I can test that again when I get to it (probably next week).
