### ISSUE TITLE
TiDB

### ISSUE THREAD

**Issue by MateusAmin** [ory/kratos#1551]
Hacking my way to get Kratos to work with TiDB. TiDB is mostly compatible with MySQL.

**Comment by MateusAmin** [comment]
My current road bump is that it doesn't allow the transaction level to be serializable. However it will if I set this flag:

SET SESSION tidb_skip_isolation_level_check = 0;

**Comment by MateusAmin** [comment]
Looking around, found this: https://github.com/ory/x/blob/master/popx/transaction.go

Getting a bit late here, might pick it up in the morning.

**Comment by MateusAmin** [comment]
https://github.com/ory/x/blob/3c08c19212e51f5687ae2b0968440207f5f0c77b/popx/migrator.go#L305

**Comment by aeneasr** [comment]
> Will setting this to LevelRepeatableRead have a detrimental effect? Does the migrator need LevelSerializable? I imagine reducing the strictness will increase compatibility.

Yeah, migrations need the highest isolation level to avoid concurrent migrations runners (e.g. k8s misconfig) from messing up the DB.

**Comment by MateusAmin** [comment]
Makes sense.

In TiDBs case, it supports [Snapshot Isolation](https://jepsen.io/consistency/models/snapshot-isolation) but [uses Repeatable Read since the SQL-92 standard does not define Snapshot Isolation and Repeatable Read is the closest model](
https://pkg.go.dev/database/sql#IsolationLevel).

Snapshot Isolation should be able to handle concurrent migration runners. If the migration runner is reading the schema version and committing the changes in same transaction. In two competing transactions since the schema version is always written two one will abort.

For the time being I am going to drop it to LevelRepeatableRead and see where that gets me. If it gets me far I will circle back to this and think it through more. The solution off the cuff would be if TiDB set to LevelRepeatableRead.

**Comment by MateusAmin** [comment]
Changed the isolation level to Repeatable Read. Migration and serve working.

**Comment by MateusAmin** [comment]
As it works out of the box with a one line change I imagine a proper PR is not too much work. Definitionally down to do it if there are more interested parties.

**Comment by aeneasr** [comment]
Thank you for the updates! If the PR means that we have to move away from serializable, I think it would not be acceptable as that can have unintended consequences in all other databases. As you can see, only serializable has the appropriate isolation level (taken from the linked docs page):

<img width="1325" alt="Bildschirmfoto 2021-07-23 um 16 43 10" src="https://user-images.githubusercontent.com/3372410/127228204-7a56a39f-d5fc-43e6-b01c-a45b1fd07a59.png">

Given that you can disable the isolation level check using `SET tidb_skip_isolation_level_check = 0` I think there is an appropriate workaround available as we currently do not wish to add another officially supported database to the mix (which would require functional testing, integration testing, e2e testing and would increase the CI time by quite a bit).

So if I understood everything correctly:

1. Moving away from SERIALIZABLE is not desirable for all databases except for TiDB;
2. There is a workaround available for TiDB by disabling isolation level checking;
3. There is no desire to add official support for TiDB due to CI build times, but we can obviously add a docs page explaining how to use TiDB if desired (by using the workaround).

**Comment by MateusAmin** [comment]
Thanks for looking. Not a big deal on my end. We are considering a TiDB solution in case scaling becomes an issue.

My thinking was to a PR that set the session variable ```tidb_skip_isolation_level_check``` for the migrator only if TiDB was being used.

I will go ahead and close the issue. If we go through with a migration I will update this issue and the docs with workarounds.

**Comment by siennathesane** [comment]
I would like to reopen this issue as I have opened a PR, ory/pop#11, that adds TiDB support in a very maintainable way.

**Comment by vinckr** [comment]
Hey @siennathesane feel free to open a new issue for this so we don't have to wade through 5 year old discussions :)
