### ISSUE TITLE
Support FIDO2 2fa / passwordless login 

### ISSUE THREAD

**Issue by arianvp** [ory/kratos#158]
I would like to use Webauthn/ FIDO2 hardware tokens for 2fa  (https://webauthn.io)

**Describe the solution you'd like**

There is a library in go that implements this https://github.com/duo-labs/webauthn
perhaps it would be interesting to integrate with kratos?  I'd be open for doing A PR for this if this is something you would like to see in your product.

**Describe alternatives you've considered**

None yet.

**Additional context**

None yet.

**Comment by aeneasr** [comment]
Yes, absolutely! Architecture-wise the plan is to have a 2fa strategy (similar to login/registration/...) and then several packages (such as webauthn as well as google authenticator, ...) for each individual strategy.

Regarding the 2fa strategy and subsequent implementation of webauthn, we'd happily accept any help. We would need to design the flows though, maybe in a hangout or some other web conference, because there are certain security implications one needs to be aware of, and also regarding the developer user experience. Would you be interested in that? I know that it's a bit of a time commitment, but it would advance the release timeline of kratos significantly!

**Comment by arianvp** [comment]
Note that webauthn can also be used to implement so-called "passwordless" flows where the password is not sent to the website; but sent to the authenticator instead.    Is that also something Kratos would be interested in?

I don't have any time to work on this in the coming time; but I just wanted to add context to the ticket.  

Happy to help anybody who wants to work on it though by explaining some of the webauthn concepts

**Comment by nerrixDE** [comment]
As the OP suggested this is a dupe and might be closed
