### ISSUE TITLE
Ensure proper playground usage & versioning

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#1635]
**The Promblem**

Currently in the docs we have references to the playground Kratos. Especially in the quickstart it does not make sense to have a docker compose but additionally references to the playground (see e.g. #1626).

Furthermore, the playground needs versioning or some kind of handling not-compatible versions. 

**Ideas**

It might be a good idea to have a playground and a docker compose qickstart. The playground one can then be removed for the non-latest releases as it might not be as relevant anymore anyway.

**Comment by vinckr** [comment]
As I understand it the playground is for the Ory Cloud? 
IMO it would make sense to have guides specific to Ory Cloud not in the Open Source docs.

**Comment by aeneasr** [comment]
> IMO it would make sense to have guides specific to Ory Cloud not in the Open Source docs.

The playground offers a really nice way to try out Kratos without running it locally. I agree that the Docker quickstart should use Docker only, and the cloud quickstarts should live in ory/docs!

**Comment by vinckr** [comment]
I tried making some curl requests to the playground but I always get 
```
{
  "error": {
    "code": 403,
    "status": "Forbidden",
    "request": "6925a82d9f8df35cbb4ca18794d999f7",
    "reason": "The request was rejected to protect you from Cross-Site-Request-Forgery (CSRF) which could cause account takeover, leaking personal information, and other serious security issues.",
    "details": {
      "docs": "https://www.ory.sh/kratos/docs/debug/csrf",
      "hint": "The anti-CSRF cookie was found but the CSRF token was not included in the HTTP request body (csrf_token) nor in the HTTP Header (X-CSRF-Token).",
      "reject_reason": "The HTTP Cookie Header was set and a CSRF token was sent but they do not match. We recommend deleting all cookies for this domain and retrying the flow."
    },
    "message": "the request was rejected to protect you from Cross-Site-Request-Forgery"
  }
}
```
e.g. for 
`curl -s "https://playground.projects.oryapis.com/api/kratos/public/self-service/registration/flows?id=d1e5f66a-db28-432a-bdae-b52d6bd0bcde" | jq`

`curl -s "https://playground.projects.oryapis.com/api/kratos/public/self-service/registration/flows?id=<flow_id>" \  | jq`
is part of the quickstart too, that why I was wondering if this is 
an error on my end or should you get a proper response as in the example further down in [quickstart](https://www.ory.sh/kratos/docs/next/quickstart/#perform-registration-login-and-logout)?

Is this because of:
`To prevent several attack vectors, Ory Krato's Public API is protected - even for some GET requests - with Anti-CSRF measures.`
and it used to not be protected in the playground? 

Just wanted to clear this up before I procceed with the playground example.

**Comment by aeneasr** [comment]
Where did you get the curl requests from? :)

**Comment by vinckr** [comment]
The second example in the quickstart here: [Perform Registration, Login, and Logout](https://www.ory.sh/kratos/docs/next/quickstart/#perform-registration-login-and-logout).
Just under
`The error message is coming directly from Ory Kratos' Admin API:`

**Comment by aeneasr** [comment]
I see, let's remove the playground there and use the localhost URLs instead as with the other examples on that page

**Comment by aeneasr** [comment]
Can you do that?

**Comment by vinckr** [comment]
Yes, will do. 
Later on, I can add a quickstart that uses the [playground](https://github.com/ory/kratos/issues/1635#issuecomment-907070763), just to show the flows, UI and so on;  
but the API calls won't work from console there, correct?

**Comment by aeneasr** [comment]
Yes, however it will be a bit of work as you need to get cookies working now with CSRF :) CURL does not store them per default, which is why you see the error atm.

**Comment by aeneasr** [comment]
Hm, thinking about it, this will also fail if we do it against localhost with CSRF. The example is not really good because you can not take the flow ID from the browser and use it in curl - it will fail. Maybe something like this here to show the example payload is better: https://www.ory.sh/kratos/docs/self-service/flows/user-login#login-flow-payloads
