### ISSUE TITLE
Linux installer cannot find the download link without explicitly set the release tag

### ISSUE THREAD

**Issue by emrahcom** [ory/kratos#1650]
When I try to download the latest version without explicitly set the tag using the Linux installer, it cannot find the download link.

```bash
bash <(curl https://raw.githubusercontent.com/ory/kratos/v0.7.1-alpha.1/install.sh) -b .

>>> ory/kratos info checking GitHub for latest tag
>>> ory/kratos crit unable to find '' - use 'latest' or see https://github.com/ory/kratos/releases for details

bash <(curl https://raw.githubusercontent.com/ory/kratos/v0.7.1-alpha.1/install.sh) -b . latest

>>> ory/kratos info checking GitHub for tag 'latest'
>>> ory/kratos crit unable to find 'latest' - use 'latest' or see https://github.com/ory/kratos/releases for details
```

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment.

If you have used an issue template and see this comment, it means that your description lacks information that allows maintainers to understand what problem you are facing and how to reproduce it.

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed. Thank you for your understanding!

---

In particular: OS version and arch missing

**Comment by emrahcom** [comment]
> In particular: OS version and arch missing

Debian 11 Bullseye, amd64

`uname -a` output:
```
Linux eb-test 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux
```

**Comment by emrahcom** [comment]
I checked the installer code and the issue seems related with [this line](https://github.com/ory/kratos/blob/master/install.sh#L276). I get `406 Not Acceptable` for this line.

```bash
curl -w '%{http_code}' -sL -H "Accept:application/json" https://github.com/ory/kratos/releases/latest
406
```

The same method works for hydra repo
```bash
curl -w '%{http_code}' -sL -H "Accept:application/json" https://github.com/ory/hydra/releases/latest
{"id":46196066,"tag_name":"v1.10.3","update_url":"/ory/hydra/releases/tag/v1.10.3","update_authenticity_token":"wmRyClamfcWErd8NEIMTNRso2z5uPoO3VHBuAC0XQqRNjNBjOsyA5nVLtnzLsT5y5vfHEvrFBo9aLoizxAddZw==","delete_url":"/ory/hydra/releases/tag/v1.10.3","delete_authenticity_token":"G/2BMjNesh7LD69IEaq3z0cZhcG8D7co/FlEhcTB/uqLGeNEMtD2Yge1mND9dLt8mokMdqXk6n4WyKdEeEZwgA==","edit_url":"/ory/hydra/releases/edit/v1.10.3"}200root@test-bullseye:
```

**Comment by aeneasr** [comment]
Hm, the problem could be that we have only pre-releases so far?

**Comment by emrahcom** [comment]
I think so. Then I'm closing this issue. I'll check it again after release.

thanks @aeneasr

**Comment by aeneasr** [comment]
Thank you! Where did you find the original instruction? We should definitely update the docs for it!

**Comment by emrahcom** [comment]
https://www.ory.sh/kratos/docs/reference/configuration/

_If file $HOME/.kratos.yaml exists, it will be used as a configuration file_

**Comment by emrahcom** [comment]
I don't remember if I read a related line in the instruction (_I did a quick search but I couldn't find anything related_). Probably I checked the shell script code and decided to try it since it seems OK according to the codes.

While installing using `install.sh` there is a message like the following

```bash
bash <(curl -s https://raw.githubusercontent.com/ory/kratos/v0.7.1-alpha.1/install.sh) -b .
ory/kratos info checking GitHub for latest tag
ory/kratos crit unable to find '' - use 'latest' or see https://github.com/ory/kratos/releases for details
```

**Comment by aeneasr** [comment]
I see, thank you! Yeah that message is definitely a bit confusing. Unfortunately the file is autogenerated and the project that generates it is unmaintained.
