### ISSUE TITLE
Ask to re-authenticate despite only updating non-privileged fields.

### ISSUE THREAD

**Issue by Quasarman** [ory/kratos#1889]
**Describe the bug**

When wanting to update non-privileged traits like first/last names of an identity and the ```privileged_session_max_age``` has already passed I get an error stating the the login session needs to be refreshed (error.id === ```session_refresh_required```). From the documentation I see that this should only be the case for sensitive fields like the password, username and email.

![image](https://user-images.githubusercontent.com/30523269/138944723-89f6426a-669c-4ab9-a530-cb88ffe1fada.png)

The request payload I am sending (Note: neither the username, email or tos_accepted fields have changed. I only supplied them in the payload so it wont cause other errors telling me that required fields are missing.) I just want to update the first_name trait.

![image](https://user-images.githubusercontent.com/30523269/138945368-57c4f1d9-5333-4fba-86e2-1b29aa5941bf.png)

The response I got after waiting for ```privileged_session_max_age``` time to pass.

![image](https://user-images.githubusercontent.com/30523269/138945526-39f8db4e-8434-4bd1-a053-8c250b046eef.png)

I am using the "Complete Settings Flow" in "profile" mode. Is this the correct approach? Or is updating such traits handled differently?

How can I achieve updating trivial traits without asking the user to refresh their session.

**Reproducing the bug**

Waiting till the ```privileged_session_max_age``` as passed and try to modify any traits that are not security critical.

**Expected behavior**

Updating of non-privileged traits like first/last name does not require re-authentication after the ```privileged_session_max_age``` has passed.

**Environment**

Docker v0.8.0

**Additional context**

None.

**Comment by Quasarman** [comment]
Hello @aeneasr,

It seems I (and a co-worker of mine) have found the problem. Your initial thought was correct. It appears when having both the email and the username set as a password identifier non-privileged fields are no longer editable without a valid session. We modified the quickstart example so the username also has the password identifier. After that change the settings flow always needs a privileged login session regardless of the trait that changes value (even of trivial fields like the first name).

## Intended Feature?

From the documentation I see that in theory setting both the email and the username as password identifiers should be a valid configuration without this side effect happening: https://www.ory.sh/kratos/docs/concepts/credentials/username-email-password#use-case-username-and-email-and-password

## Fining the Bug

I also had a look at the source code for quite some time but I simply can't wrap my head around how the comparison functions work. I identified the following sections inside the code where the bug most likely must occur given the circumstances:

* https://github.com/ory/kratos/blob/master/selfservice/flow/settings/hook.go#L150
* https://github.com/ory/kratos/blob/4b9da3c9d98d40f7b71a56c51543fc115974630d/identity/manager.go#L91
* https://github.com/ory/kratos/blob/4b9da3c9d98d40f7b71a56c51543fc115974630d/identity/credentials.go#L114
* https://github.com/ory/kratos/blob/4b9da3c9d98d40f7b71a56c51543fc115974630d/identity/manager.go#L72

Any further help/investigation regarding solving this issue is well appreciated :)

**Comment by aeneasr** [comment]
Thank you for the trace! I believe the issue is one of ordering. I think that if we have two credentials, they might be stored in a map, so that the two credentials are swapped around. Or another issue might be that the comparison is not properly working if we have two credentials. I think this file is the place to look into:

https://github.com/ory/kratos/blob/4b9da3c9d98d40f7b71a56c51543fc115974630d/identity/manager.go#L72

Writing a test like

https://github.com/ory/kratos/blob/4b9da3c9d98d40f7b71a56c51543fc115974630d/identity/manager_test.go#L94-L109

but with multiple fields could probably investigate this!

Would you be open doing so? The issue you have found is definitely a bug!

**Comment by codetent** [comment]
Hi @aeneasr,

@Quasarman  and I debugged this a little bit deeper and found out that actually 2 independent issues are causing this problem:

## 1.  Specifying multiple identifiers

It seems that having two fields in the identity like email and username which can both be used for logging in, it is always asked for re-authentication when changing unprotected traits.

### Steps to reproduce

We did the following steps when trying it with the quickstart example:

1. Add a field to the `identity.schema.json` like:
    ```json
    "username": {
      "type": "string",
      "minLength": 3,
      "ory.sh/kratos": {
        "credentials": {
          "password": {
            "identifier": true
          }
        }
      }
    }
    ```
2. Create a user by signing up using the UI
3. Goto settings page and change `First Name`

### Potential problem

We added some additional debug logs to `requiresPrivilegedAccess` and found out that the first `if` where it compares the credentials evaluates to false. Both maps have the same keys and values but you are right, the order is different. It seems like `DeepEqual` in the `CredentialsEqual` function does only compare the key list which is in a different order. Therefore, the function returns false and it does not work.

## 2. Updating traits of verified user

It seems like as long as the user is not verified using the link in the email, traits can be changed without any problem. After the link is clicked, re-authentication is always required.

### Steps to reproduce

We did the following:

1. Keep the default settings and schema
2. Create a user by signing up using the UI
3. Click on the link in the verify email
3. Goto settings page and change `First Name`

### Potential issue

In this case, the second `if` in `requiresPrivilegedAccess` evaluates to false, because `DeepEqual` of the `VerifiableAddresses` addresses returns false. Further investigation showed that the compared values are equal except the `VerifiedAt` field. The pointer address is different and also the value behind is not the same.

We checked both values by having a look at the result of the `deepcopy.Copy` call in the `SetTraits` function and it seems that after making the copy, all fields of `VerifiedAt` are set to 0 and are therefore, not the same as the original value.

**Comment by Quasarman** [comment]
Hello @aeneasr,

I know you don't give estimates when features/bug fixes will be implemented (from reading other issues and responses to them). Nevertheless I am itching to know when this fix is routhly gonna be available. Do you have a rough estimate for me?

P.S.: If not I totally understand.

BR,
Johannes

**Comment by aeneasr** [comment]
We don’t unfortunately. The fix should be relatively easy if anyone wants to pick this up!

**Comment by Quasarman** [comment]
Hello @aeneasr,

Is this on anyone's radar? It seems odd to me that no one has had a similar problem since the behavior of changing non-privileged fields without being asked to re-authenticate seems rather common. We are still having the same issues with the latest kratos version which cause some unwanted steps / errors when a user updates their profile settings (first name, last name, birthday,...).
