### ISSUE TITLE
Partial profile / settings update

### ISSUE THREAD

**Issue by viters** [ory/kratos#2021]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

User can have multiple traits, there may be business flows when only part of them should be updated. Not all of them should require the same AAL / privileged session.

### Describe your ideal solution

Define AAL / privileged session requirement by trait. Allow to send partial profile updates.

### Workarounds or alternatives

None

### Version

0.8

**Comment by aeneasr** [comment]
That makes sense - currently it is not possible to differentiate using configuration what's privileged and what isn't! So it's always meta info like recovery email or something similar that will cause the privileged check. I think it should be easy to add this to the JSON Identity Meta Schema :)

**Comment by zepatrik** [comment]
This needs the following changes:

- add a field to the Ory schema extension: https://github.com/ory/kratos/blob/61ce3c0c35366f587bfee5c89496fa15432bb241/schema/extension.go
- adjust AAL logic to respect the setting based on what traits are actually updated: https://github.com/ory/kratos/blob/61ce3c0c35366f587bfee5c89496fa15432bb241/selfservice/flow/settings/handler.go#L510

The current behavior requires to submit all traits, no matter if they changed or not. We should probably allow two cases:
- omitting some traits keys
- looking up whether the values actually changed

**Comment by aeneasr** [comment]
> looking up whether the values actually changed

This would be the preferred option!

**Comment by ankitsridhar16** [comment]
- @zepatrik the AAL logic is handled by Session Manager and does an AAL check when the session struct and the request is passed as an argument - https://github.com/ory/kratos/blob/cc99096d07408c8b713ef9a7b17b8345597a9129/session/manager_http.go#L176 . The solution you did suggest above where the logic change is required should that happen at the self-service level or should be ideally handled at the session manager level ?

- About adding a field to the schema can you tell me the flow on how extension schema works in this case and why adding a field is required in this file ?

**Comment by zepatrik** [comment]
Basically, the steps in the handler should be the following:

1. figure out what keys actually changed
2. determine the max required AAL for those keys based on a) whether they are special values and b) what is set in the identity schema
3. use the existing function to check whether the session has the required AAL

To allow setting an AAL for each key, you have to add a key to the schema extension. Same as you configure what key is used as the identifier, you can set a `require_aal.update` key. I think it makes sense to have a `required_aal` object, as we might later want to support setting a read AAL.

**Comment by Benehiko** [comment]
Hey @ankitsridhar16 

So I looked into this a bit and there are a couple of things at play with this flow. I will highlight everything in this comment so it's a bit more clear what needs to be changed.

When we do an update, it can be a variety of strategies, e.g. `password`,`oidc`, `totp` etc. update. With that said, some things automatically require `aal1` or `aal2`. See the [docs here](https://www.ory.sh/docs/kratos/guides/two-factor-authentication-2fa-mfa#strict-and-lax-multi-factor-authentication).

The `submitSettingsFlow` does a couple of things before even checking the strategy. 
https://github.com/ory/kratos/blob/668f6b246db1f61b9800f7581bedba4fa25318c4/selfservice/flow/settings/handler.go#L488

1. It checks the Flow ID
https://github.com/ory/kratos/blob/668f6b246db1f61b9800f7581bedba4fa25318c4/selfservice/flow/settings/handler.go#L495-L502

2. Gets the session (which includes the identity and its traits)
https://github.com/ory/kratos/blob/668f6b246db1f61b9800f7581bedba4fa25318c4/selfservice/flow/settings/handler.go#L504-L508

3. Validates the `aal` by getting the highest available (default) or through a config value `selfservice.flows.settings.required_aal`
https://github.com/ory/kratos/blob/668f6b246db1f61b9800f7581bedba4fa25318c4/selfservice/flow/settings/handler.go#L510-L513

4. It then goes through all the strategies and updates the values (depending on the strategy)
https://github.com/ory/kratos/blob/668f6b246db1f61b9800f7581bedba4fa25318c4/selfservice/flow/settings/handler.go#L522-L536

--- 

In this case I will follow the `profile` strategy since this is the feature we want to update. Here we can see the request data being decoded and the JSON validated.
https://github.com/ory/kratos/blob/151c8cfb53402aaf2518a471579c25c3785b13d2/selfservice/strategy/profile/strategy.go#L129-L135

It then goes on to update the traits here
https://github.com/ory/kratos/blob/151c8cfb53402aaf2518a471579c25c3785b13d2/selfservice/strategy/profile/strategy.go#L140-L142

and digging deeper, specifically here:
https://github.com/ory/kratos/blob/151c8cfb53402aaf2518a471579c25c3785b13d2/selfservice/strategy/profile/strategy.go#L170-L176

This code also validates the traits against our json schema and json schema extension.
We would probably need a property inside the json schema extension as @zepatrik mentioned `require_aal`.

https://github.com/ory/kratos/blob/049fd8edc382f344018398027a4e0b3915116ff2/embedx/identity_extension.schema.json#L11-L23

and our struct
https://github.com/ory/kratos/blob/1a8b256cca33aa9cbb143e7e8fc1efc8217e9b8a/schema/extension.go#L19-L44

--- 

To debug this and validate how the flow works, we can follow it by running this test and setting breakpoints inside our `submitSettingsFlow` handler.
https://github.com/ory/kratos/blob/e4f205d69bec07a71bf1d34d97ab3a6b99a4cc46/selfservice/strategy/profile/strategy_test.go#L444-L447

---

So to clarify, since there are a couple of places the `aal` is set by default through highest available and through the configuration, we need to determine if the request is only doing a `profile` update and if so, which fields. 
1. Depending on the fields that have changed we only update those
2. According to the traits sent we need to get the highest `aal` required instead of relying on the defaults or the configuration (unless of course the field is privileged e.g `email` trait). Privileged fields can be determined through using the schema extension. Check the [docs here](https://www.ory.sh/docs/kratos/concepts/identity-schema#identity-schema-vocabulary-extensions) for more information on that.
3. Allow partial updates, e.g. does not require sending `traits.email`, but allows `traits.firstName` only.

**Comment by ankitsridhar16** [comment]
@Benehiko the traits which we decode from the request and populate in type `submitSelfServiceSettingsFlowWithProfileMethodBody` already has the traits that we need to update right rather than all traits? If not so under https://github.com/ory/kratos/blob/151c8cfb53402aaf2518a471579c25c3785b13d2/selfservice/strategy/profile/strategy.go#L111 should be a place to implement the compare logic where I check the existing traits from session and the incoming request traits after decoding for which values have changed and append them to a temporary variable and dispatch it to `SetTraits()`  ?
