### ISSUE TITLE
Documentation for self-service is confusing about what is the difference between browser and API flows

### ISSUE THREAD

**Issue by mitar** [ory/kratos#2043]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I am reading [documentation](https://www.ory.sh/kratos/docs/next/self-service/) and I must say I do not get what is the difference between browser and API flows. The issue is also that flow diagrams are almost exactly the same:

![Screenshot 2021-12-08 at 02-23-50 Self-Service Flows Ory Kratos](https://user-images.githubusercontent.com/585279/145131665-6a888e52-1ef1-4b18-b515-54ffedecd65a.png)

![Screenshot 2021-12-08 at 02-23-30 Self-Service Flows Ory Kratos](https://user-images.githubusercontent.com/585279/145131669-8b08c216-ea22-49c3-ac29-f6754f36e54e.png)

So the only difference is that browser flow sets cookies while API flow does not? So if your HTTP client for API calls respect cookies you could also call browser flow endpoints and have the same behavior?

The following text confuses me:

> While the Browser flow redirects the client and uses cookies to protect against CSRF and session hijacking attacks, the API flow answers with a fresh flow formatted as application/json right away. The client would then use that information to render the UI. 

I do not think browser flow redirects at all? Both the API and browser flows answer with application/json right away. No?

### Reproducing the bug

See description.

### Version

v0.8.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker Compose

**Comment by mitar** [comment]
So I think this should be expanded what exactly is problematic from security perspective. And I must say I do not get why SPA could not call APIs directly. CSRF is not possible because authorization header is used instead of a cookie. Is this because some additional confidential data is necessary for API calls beyond user token, and SPAs cannot have that confidential data? But native apps cannot have it either.

So what is difference between native apps and browsers? I do not see many, except how they render UI. So what is security implication here?

Is it only that it is problematic to persist token in SPA into localStorage vs. cookies? But that is a minor difference. Not sure if it really makes sense to have the whole separate set of API endpoints just for that?

**Comment by aeneasr** [comment]
> So I think this should be expanded what exactly is problematic from security perspective. And I must say I do not get why SPA could not call APIs directly. CSRF is not possible because authorization header is used instead of a cookie. Is this because some additional confidential data is necessary for API calls beyond user token, and SPAs cannot have that confidential data? But native apps cannot have it either.
>
> So what is difference between native apps and browsers? I do not see many, except how they render UI. So what is security implication here?
> 
> Is it only that it is problematic to persist token in SPA into localStorage vs. cookies? But that is a minor difference. Not sure if it really makes sense to have the whole separate set of API endpoints just for that?

Browsers have cookies, thus, they are vulnerable to CSRF. It does not matter what application you render in the Browser. It's the browser, not the app.

Additionally, any user without a session has no credentials, thus no session, thus no cookie and no token. Anti-CSRF cookies work with and without sessions, because it is always issued, not only on login.

CSRF vulnerabilities against log in are, by the way, a very common vulnerability. But sessions are not Anti-CSRF measures, they're sessions proving who you are and not what context you are in :)

**Comment by mitar** [comment]
Hm, what I do not understand is why there have to be two sets of endpoints. Why simply not have one set of endpoints which behave like:
* If there is an `Authorization` header, validate it, accept the API call.
* Otherwise, if there is a `Cookie` header with session token, require also CSRF cookie, validate both, accept the API call.
* Otherwise, it it is a login call without a session token in the cookie, require CSRF cookie, validate it, accept the API call if credentials match.
* Otherwise, reject the API call.

I do not see how would this be vulnerable? Am I missing something?

**Comment by mitar** [comment]
My main motivation here is that if we can make Kratos API operate in secure way automatically, without developer have to pick one or the other set of API endpoints for that, we get rid of one whole set of potential issues developers using Kratos might have. Documentation is warning well what to use and what not, but ideally one would not have to think about that and Kratos would just do the right thing.

**Comment by aeneasr** [comment]
> Otherwise, it it is a login call without a session token in the cookie, require CSRF cookie, validate it, accept the API call if credentials match.

Could you elaborate what „if credentials match“ means? Keep in mind that we have more than log in flows (recovery, verification, …)

**Comment by mitar** [comment]
> Could you elaborate what „if credentials match“ means? Keep in mind that we have more than log in flows (recovery, verification, …)

Sure. So that is the POST/form submission, you can get password in the submission, or recovery token, verification token. So all that (for different flows) is compared against the database and if it matches, the API call is accepted. And the call always requires CSRF protection.

Are you saying that login and recovery flow is also something one would do as a regular API call? Then yes, those cannot be without CSRF protection in my scheme. But that can be addressed in different ways than having whole additional set of API endpoints:

* You require also API callers to obtain a CSRF token by calling some dummy endpoint first.
* They can opt-in into no CSRF by passing a header or query string argument. So using the same API endpoint, only opt-in into not requiring a cookie.

**Comment by aeneasr** [comment]
I fear I don't agree with the proposed API design. I would also like to generally have no CSRF tokens at all, because people struggle with it. But that doesn't mean we can nullify them, or end up with a design that has some init endpoints for some interactions and no such endpoints for others.

These guiding principles are the basis for the decisions:

1. We have to force developers to use anti CSRF measures in browsers because if they have a choice they will choose not to do it;
2. We have to establish intent to deploy the appropriate security measures, meaning the developer "tells us" whether they want to use a browser or not;
3. We have to enforce anti-CSRF if the intent is to use a browser;
4. If the developer misleads us and says "my intent is not a browser" and we see that it is in fact a browser, we disallow the request to keep the system secure;
5. If the intent is "I do not have a browser" (and thus CSRF does not apply to me) and in fact, the client is not a browser, we can disable CSRF.

Back to your points:

1. A password is not an Anti-CSRF measure. Please read how anti-CSRF works and why it's important: https://cheatsheetseries.owasp.org/cheatsheets/Cross-Site_Request_Forgery_Prevention_Cheat_Sheet.html
1. An Anti-CSRF measure always implies that we have one thing persistent on the client (**cookie**), and another that is part of the submission payload. A password is persistent for the user, not the client. It is not a cookie, it's a secret.
1. A recovery token is issued **after** the user clicks the email link. The form submission, **which is why we do anti-CSRF** does not care about the token when you enter your email address;

Somehow squeezing in CSRF through passwords or links or some headers is just way more confusing. Let's clean up the docs, explain why we have to flow types and we're good to go.

I am also happy to review any concrete flow diagrams that explain a better approach than what we have today, because we want to improve this. But it needs to be consistent, work for all form submission types, work in all scenarios, and follow the guiding principles from above.

**Comment by mitar** [comment]
Sorry for late response.

I think there was some misunderstanding because I never claimed that the password is an anti-CSRF measure, so there is no point in arguing that, sorry if I made you somehow feel that I am saying that and you arguing that point.

Let me maybe explain it from the other angle, the same thing, but maybe it will be clearer what I am saying.

What I think we both agree on that we have two types of requests, one from browsers and one from backend clients, with different security properties. Currently, Kratos differentiate between those types of requests based on the URL: one set of URLs is for browsers, another set of URLs is for backends (in fact, just the suffix of the URL is different, `/browser` vs. `/api`). That is fine, but to me it feels very crude. What I am proposing is that instead of using the suffix of the URL to know which request is for what, is to use some other part of the HTTP request (query string, a header). What I am saying is that default behavior would be the one of `/browser` (so anti-CSRF measure is required) and one has to opt-in into the `/api` one, but not by changing the URL, but by appending a query string or even better, a custom header (which is something easy to do from the backend client but harder to do from a browser), e.g., `X-I-Really-Am-A-Backend-Client: true`. Why I think it is a better approach:

* It simplifies documentation: one has everything the same, with one paragraph saying that if you want to call from backend, you should include this additional header.
* Not all API endpoints require an anti-CSRF measure, so instead of having to have duplicate set of all API endpoints, just those sensitive API endpoints can be handled specially (can require this additional header).
* For authenticated API endpoints we can even detect if anti-CSRF measure is needed: if authentication for the API endpoint comes with `Authorization` header, then we know we do not need an anti-CSRF measure, no matter where is the request coming from, browser or backend client.

One alternative to the custom header which I proposed above is that maybe the simplest approach is that anti-CSRF is required also for backend clients. That could be addressed an API endpoint (which should not have CORS headers) which returns the CSRF token to be used. So backend clients might be slightly more complicated, but that is maybe a good trade off to have consistent API. (In this case `X-I-Really-Am-A-Backend-Client` can be simply renamed to `X-CSRF-Token: <token from the API endpoint>`.)

**Comment by aeneasr** [comment]
Thank you for elaborating! That is true, we could combine this into one endpoint and use (e.g.) `?noBrowser=true` which probably is less confusing. It might also be a good idea to calm this param something like `noBrowser` as it indicates that we don’t have a browser and are thus less likely to be victim of CSRF!

**Comment by mitar** [comment]
Yea. Or even something like `disableCsrfProtection=true` to be pretty clear and explicit what you are doing.

**Comment by aeneasr** [comment]
The problem here is that we need to force devs to do things securely. There’s a lot of people who’d happily disable CSRF if they could because it’s easier! So I think the intent in which you use the APIs should be clear, and not particularly what security features you want to use or not

**Comment by mitar** [comment]
I do not think naming really forces anyone to do anything. At least any audit will have easy time noticing somebody is disabling CSRF. :-)

But this is a minor point. Use whichever name you like. :-)

**Comment by masterbater** [comment]
Is there any way in the future that you could support jwt tokens and use that for spa access token and refresh token? 

Firebase and some auth provider they just store refresh tokens in localstorage or indexdb and their client sdk only just refresh the access token if it expires.
Firebase refresh tokens does not expire too only in this case 
https://firebase.google.com/docs/auth/admin/manage-sessions
The user gets deleted
The user updates their email
The user updates their password

Is firebase auth implementation not secure?
Ory Browser flow seems complicated but secure and has more features than firebase.

**Comment by viters** [comment]
> So I think this should be expanded what exactly is problematic from security perspective. And I must say I do not get why SPA could not call APIs directly. CSRF is not possible because authorization header is used instead of a cookie. Is this because some additional confidential data is necessary for API calls beyond user token, and SPAs cannot have that confidential data? But native apps cannot have it either.

I would like to get back to that point. What is the CSRF threat behind SPA using `/api` flow?
- start SPA
- render login form
- put credentials, click login
- fetch call returns token
- store token in localStorage
You are not vulnerable to CSRF. You are vulnerable to XSS, because token lies within JS scope - but not CSRF. Yet docs mention CSRF, not XSS:
![image](https://user-images.githubusercontent.com/13100466/180039198-a4e45584-226a-44f7-a3c2-534ebe0b5c16.png)

**Comment by philhug** [comment]
> I would like to get back to that point. What is the CSRF threat behind SPA using `/api` flow?
> 
> * start SPA
> * render login form
> * put credentials, click login
> * async response returns token
> * store token in localStorage
> * no cookies were involved in process

This is also the flow I'd like to implement, in our SPA. It's also a lot easier if your API is not on the same url as the SPA as you don't have to share the cookie domain and can also easy develop on localhost. 
Using cookies is just a lot more painful and doesn't feel natural in SPAs.

The other thing is, the current APIs don't allow to access the session cookie in any way from javascript, so I'll have to implement a workaround similar to #2487 to exchange the kratos session cookie to a jwt, which then can be used as in the Authorization header for API calls.
