### ISSUE TITLE
How do we refresh the GitHub "traits" data whenever we update the JSONNet mapper file?

### ISSUE THREAD

**Issue by factoidforrest** [ory/kratos#2326]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Is there a way to trigger a refetch of the user's traits during an OIDC login?  It would be nice if they refetched every time the user re-authorized, so they didn't become stale.  

### Describe your ideal solution

A flag refresh-traits

### Workarounds or alternatives

we could fetch this data ourselves manually, its just more work

### Version

We built our own from v0.8.3-alpha.1.pre.0

**Comment by aeneasr** [comment]
That's unfortunately not possi ble at the moment, but a cool feature request! I think it will need quite a bit of work though, as we currently have no update capabilities in login flows.

**Comment by netthier** [comment]
Adding this feature would be very appreciated, as any changes like updated emails in the IdP should transfer to Kratos as well.

**Comment by aeneasr** [comment]
I totally agree that this is a good feature! Solving this use case is very difficult to do because we would need to add:

1. Ensure that the social sign in provider returns a refresh token and the user also agrees to it
2. A background worker that continuously refreshes all the access tokens
3. A background worker that can refresh all the claims
4. A mechanism to deal with conflicts (field a already exists but is to be updated to `abc` - what do we do?)

And in general, there will always be a non-negligible % of users that can not be refreshed for many reasons:

1. Token refreshing did not work
2. Platform changed something in the token mechanism
3. Platform revoked our tokens
4. User revoked our tokens
5. ...

So it will never be possible to have guaranteed sync.

One option though would be to allow run the jsonnet during login, which would allow us to update the traits of users.

**Comment by netthier** [comment]
> One option though would be to allow run the jsonnet during login, which would allow us to update the traits of users.

This would be sufficient for me. As far as I understand, every time a user logs in via a social login, Kratos receives a fresh access token containing all the data needed to refresh the user. 
This is also the way Keycloak solves this issue.
A background worker automatically refreshing all users would be way beyond that, and I'm not aware of any services currently implementing that.

**Comment by tdipadova3rd** [comment]
Chiming in that running jsonnet during login would solve this for us as well!

**Comment by factoidforrest** [comment]
Hi @aeneasr , just to clarify, updating during login when kratos gets a new access token is exactly what I had envisioned.  As far as I can tell, that wouldn't involve the work you mentioned.
