### ISSUE TITLE
Session identifiers should be immutable

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#2701]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

To improve session handling, we want to make session references (e.g. session cookie value, session token) immutable. Example:

1. User signs in using password, a new session (cookie value: 133) is created
2. User updates session by changing their profile, signing in using MFA, or re-authenticating the session

Currently, the session cookie value (133) remains the same, making it difficult to understand whether the session has changed.

### Describe your ideal solution

The session reference (session cookie value, session token) should instead be immutable and changed when the session's content change. Let's say you upgrade the session by performing TOTP. In that case, the server should respond with:

```
// request
POST /mfa
Cookie: ory_session=133
{ "mfa_totp": "..." }

// response
Set-Cookie: ory_session=134
```

**Affected APIs**

We will need to implement this feature inthe following APIs for the given cases:

1. Login API
    1. Re-Authentication (to e.g. change a privileged field)
    2. Session Upgrade (e.g. completing second factor)
2. Settings API
    1. Changing profile related settings (e.g. change first name)
    2. Adding a second factor (e.g. enabling TOTP for second factor, effectively upgrading the current session to 2FA)

For the Login API, these changes can easily be propagated to both the re-authentication and session-upgrade case easily for both tokens and cookies. For the settings API, we will need to identify how to notify the API (token) client that the session needs to be updated.

### Workarounds or alternatives

There are no alternatives to my knowledge.

### Version

master

### Additional Context

As the administrator, it is possible to change the traits of a user and also change the session lifetime (using session refresh). Here, we will need to make a trade off and ignore these type of changes. In that case, changes would propagate "eventually consistent" to the client. This is ok because admin and user are two different actors and hence most likely won't notice eventually consistent changes to the session if the maximum delay is acceptable (e.g. 10 seconds).

**Comment by kelkarajay** [comment]
> - Login API
>   - Re-Authentication (to e.g. change a privileged field)
>   - Session Upgrade (e.g. completing second factor)

Here's how I see these handled -

- Create a clone of the current session and refresh it's identifiers (ID, Token, LogoutToken).
- PostLoginHook takes care of revoking the old session, upsert new session and returning the new session to the consumer
- Update tests to use the token from the LoginFlowSubmit response for Re-auth and session upgrade scenario's

**Comment by kelkarajay** [comment]
@aeneasr @zepatrik I could use a review here.

Implementation approach (The login part is implemented in the linked PR - E2E tests yet to be fixed) -

Revoke current and issue new session.

## Login flow

As described below (picture), new session identifiers will be issued post **After Login hooks** execution. 

<img width="1020" alt="Screenshot 2022-10-05 at 15 15 46" src="https://user-images.githubusercontent.com/6560194/194076135-14b07ee7-4215-425e-a006-fd54f0081058.png">


## Settings flow

As described below (picture), new session identifers will be issued post **After settings hooks** execution. Handling -

### Browser clients 
- no action to do (since Set-Cookie response will overwrite)
### API clients - we have two options imo

- Update Flow response to have APIFlowResponse attribute with new token and new session, or
- Use Response Header like X-New-Session-Token which API clients have to detect and refresh when present 
_(Inconsistent with the current Login response)_

<img width="1034" alt="Screenshot 2022-10-05 at 15 20 02" src="https://user-images.githubusercontent.com/6560194/194075744-f67119f9-b48c-4132-a361-44b8709a2996.png">

**Comment by aeneasr** [comment]
Have you seen https://github.com/ory/kratos/pull/2761#discussion_r987568965 ?
