### ISSUE TITLE
pagination issue

### ISSUE THREAD

**Issue by nicolasburtey** [ory/kratos#2834]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

`kratosAdmin.adminListIdentities(1, 0)` and `kratosAdmin.adminListIdentities(1, 1)` return the same result

other pages (>1) seems to be working fine

having a higher number on `perPage` leads to the same issue:
`kratosAdmin.adminListIdentities(250, 0)` and `kratosAdmin.adminListIdentities(250, 1)` also return the same result

the number of user on the server we are testing on is 5k-ish

seems somewhat related to this bug which has not been closed without been resolved: https://github.com/ory/kratos/issues/2231

### Reproducing the bug

currently seen the issue on one of our staging environment.

DB: using cloud SQL for PostgreSQL: https://cloud.google.com/sql/postgresql

### Version

10.1

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by imix** [comment]
I and some others have the same issue. For me it looks like this:

- page=0 and page=1 produce the same result set
- page=0 Link header pointing to next=1
- page=1 Link header points to first/prev=0, next=2, last=second to last page (NB with the same result set as page=0)
- the second to last page has no Link header for next. Only prev and last

so for now it seems to be necessary to start at 1, run through next and then "guess" the last page (which is never linked in any link header).

(see also the discussion on slack: https://ory-community.slack.com/archives/C012RJ2MQ1H/p1673618866406469)

**Comment by aeneasr** [comment]
The page parameter starts at 1. See: https://www.ory.sh/docs/reference/api#tag/identity/operation/listIdentities

**Comment by imix** [comment]
I think at least my problem comes from the Link headers. If I request identities without a page number (so default = 1) then the link header looks like this:
´Link: <http://kratos:4434/identities?page=1&page_size=2&page_token=eyJvZmZzZXQiOiIyIiwidiI6Mn0&per_page=2>; rel="next",<http://kratos:4434/identities?page=3&page_size=2&page_token=eyJvZmZzZXQiOiI2IiwidiI6Mn0&per_page=2>; rel="last"´

As well I don't seem to get a Link "next/last" for the last page. (the last page in the example above would be page=4)

**Comment by aeneasr** [comment]
We most likely won't provide `Last` links in the future any more as we are moving to token pagination. Since `COUNT(id)` latency is growing linearly with the number of rows, it's too slow to count large tables (10M+ rows).

**Comment by imix** [comment]
I see. With page_token and only using the "next" link, I was not able to reach the last result set (there is no next link on the second to last). Am I using it wrong (is there some documentation?)

**Comment by DASPRiD** [comment]
I'm currently running into the same issue. For now I'll just request 1000 entries, as our user count is smaller than that, but this really needs to be addressed.

**Comment by DASPRiD** [comment]
Alright, I've been digging through the Ory code, these are my findings:

- The paginator in `pop` is based on `1`-indexed page numbers:
https://github.com/gobuffalo/pop/blob/c85387acc9a0c2edb5c6a669618eefde86cfd085/paginator.go#L56-L58
- Ory X's pagination utility, which parses and generates the paging parameters, is based on `0`-indexed page numbers:
https://github.com/ory/x/blob/master/pagination/tokenpagination/pagination.go#L72-L78

Thus when calling the endpoint without any parameters, it defaults to a page number of `0`, which pop automatically ups to `1`. Next, Ory X generates the next (and last) link, which points to page number `1`.

From pop's perspective, this is the same page, so the same values are being returned. From Ory's perspective this is the last page, so no more pages are returned.

I'm not too confident in how to go forward with this, but I see the following two solutions:

1. The simplest and least disruptive solution would be to pass `params.Page + 1` to the query builder:
https://github.com/ory/kratos/blob/master/persistence/sql/identity/persister_identity.go#L693
This goes against the documentation though, which states that page numbers start with `1`.
2. The probably more correct solution would be to fix `ory/x/pagination` in multiple places and change the page calculations to be `1` instead of `0` based.

**Comment by aeneasr** [comment]
This is fixed
