### ISSUE TITLE
Quickstart app doubt for authentication only(not authorization) with mysql database 

### ISSUE THREAD

**Issue by aryanPatilhm2** [ory/kratos#297]
Hii...I am trying to use the ory cratos and oathkeeper for authentication and user-management. Because I have checked that oathkeeper provide support to add custom issuer rather than domain URL. I checked the quickstart application. It has both authentication and autherization. Whenever I try to remove the authorization rules from the application, it fail to start the app. 
It  gives error like,
```
CSRF token is missing or invalid
```
Some time
```
{"error":{"code":404,"status":"Not Found","message":"Requested url does not match any rules"}}
```
Also Does it require to provide the redirection url with actual domain? Is there any support to redirect url for path taking existing domain? 

Another question is, Can we provide our own database to store the user information like mysql?  I didn't found any relevant example to use oathkeeper and cratos with another database for authentication only. Can you help me regarding this..?

Thanks in advance..

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.
