### ISSUE TITLE
Hook for recovery flow to required verified account

### ISSUE THREAD

**Issue by xbitres** [ory/kratos#3069]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Unverified accounts can trigger a request to recover their account, even though it has not been verified yet.

### Describe your ideal solution

Have a before hook on the recovery flow that would the same as the `require_verified_address ` hook for the `after` login flow.

### Workarounds or alternatives

None so far.

### Version

0.0.9

**Comment by aeneasr** [comment]
I'm not quite sure if I see the use case here. If you require verified email to recover, you're doing the same thing twice:

1. Send email to user with a link to verify the email
2. Send email to same user with another link; but this time it recovers

From a UX perspective, that doesn't make a lot of sense because you're doing the same thing twice with a slightly different end result.

**Comment by xbitres** [comment]
Is it the case then that when you have an unverified account, with then resets the password that the account gets automatically verified?

**Comment by aeneasr** [comment]
Yes
