### ISSUE TITLE
Add support of multiple tenants

### ISSUE THREAD

**Issue by testtesttesttesttsetset** [ory/kratos#3129]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I would like to have a single ory kratos instance manage identities for multiple separate tenants (as opposed to hosting multiple instances of kratos, one per tenant)

### Describe your ideal solution

Add support for tenancy (parent of flows for example)

### Workarounds or alternatives

Multiple instances of kratos

### Version

n/a

**Comment by aeneasr** [comment]
Hi, thank you for the request. This is unfortunately out of scope for this project

**Comment by marius-nicolae** [comment]
Hi,
@aeneasr why do you say it's "out of scope for this project"? I also value such a feature and think it's preferable over creating a new DB for each tenant. Keycloak has it and I love it!

**Comment by aeneasr** [comment]
Ory Kratos will never support multi-tenancy out of the box due to the complexity involved. They only way to get multi-tenancy in Ory Kratos is by using the Ory Network, which does have multi-tenancy built in

**Comment by thomastthai** [comment]
I understand the issue is closed. Since I was looking into multi-tenancy, I wanted to share some untested thoughts.

Isn't there code in Kratos for multi-tenancy (but requires a commercial license)?

Another possible approach:

Here is an illustrated example of how to implement multi-tenancy using the "Logical Separation with a `tenantId`" approach with ORY Oathkeeper and the broader ORY ecosystem.

### **Concept Overview**

In this model, a single, shared ORY Stack (Oathkeeper, Kratos, Keto) serves all tenants. The separation between tenants is not physical (i.e., not separate databases or instances) but logical, enforced by a `tenant_id` associated with each user's identity. This `tenant_id` is then used by the authorization layer (Keto) and the upstream application to control access and scope data.

### **Component Configuration and Data Examples**

Let's break down what each piece of the puzzle looks like.

#### **1\. ORY Kratos: Storing the `tenant_id`**

First, you need to configure ORY Kratos to include a `tenant_id` in the identity schema. This is done in your Kratos `identity.schema.json` configuration file.

**`kratos/identity.schema.json`:**


```json
{
  "$id": "https://myapp.com/kratos/identity.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Person",
  "type": "object",
  "properties": {
    "traits": {
      "type": "object",
      "properties": {
        "email": {
          "type": "string",
          "format": "email",
          "title": "E-Mail"
        },
        "name": {
          "type": "string",
          "title": "Full Name"
        },
        "tenant_id": {
          "type": "string",
          "title": "Tenant ID",
          "ory.sh/kratos": {
            "credentials": {
              "password": {
                "identifier": true
              }
            }
          }
        }
      },
      "required": ["email", "tenant_id"]
    }
  }
}
```

When a user signs up, your registration UI will pass the `tenant_id` along with their other traits (like email).

**Example User Identity in Kratos:**

Here's what the identity object for a user belonging to "tenant-a" would look like when you retrieve it from Kratos:

```json
{
  "id": "a1b2c3d4-e5f6-7890-1234-567890abcdef",
  "default",
  "schema_url": "https://myapp.com/kratos/identity.schema.json",
  "traits": {
    "email": "user.one@tenant-a.com",
    "name": "Alice",
    "tenant_id": "tenant-a"
  }
}
```

___

#### **2\. ORY Oathkeeper: Forwarding the Identity**

Next, configure Oathkeeper to forward the user's identity information (including the `tenant_id`) as a header to your upstream application. This is done using the `header` mutator in an access rule.

**`oathkeeper/access-rules.yml`:**

```yaml
- id: "protected-app-rule"
  upstream:
    url: "http://my-upstream-app:8080"
  match:
    url: "<http|https>://myapp.com/<.*>"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: keto_engine_acp_ory
    config:
      base_url: http://keto:4466
  mutators:
    - handler: header
      config:
        headers:
          X-User-Id: "{{ .Subject }}"
          X-Tenant-Id: "{{ .Authentication.Extra.tenant_id }}"
          X-User-Email: "{{ .Authentication.Extra.email }}"
```

-   `{{ .Authentication.Extra.tenant_id }}`: This part of the template extracts the `tenant_id` from the Kratos session payload and injects it into the `X-Tenant-Id` header.

___

#### **3\. ORY Keto: Enforcing Tenant-Based Access**

Now, you can create authorization policies in ORY Keto that use the `tenant_id` to ensure users can only access resources belonging to their tenant.

**Example Keto Policies (`policies.json`):**

```json
[
  {
    "description": "Allow members of a tenant to read products within their own tenant",
    "subjects": ["<.*>"],
    "actions": ["read"],
    "resources": ["urn:myapp:products:<(tenant-a|tenant-b|tenant-c)>"],
    "effect": "allow",
    "conditions": {
      "tenant_match": {
        "type": "StringEqualCondition",
        "options": {
          "equals": "{{ .Resource.Name | regexReplace \"urn:myapp:products:(.*)\" \"$1\" }}",
          "subject": "{{ .Subject.tenant_id }}"
        }
      }
    }
  }
]
```

-   **How this policy works:**
    -   It applies to any subject (`<.*>`).
    -   It governs the `read` action on resources like `urn:myapp:products:tenant-a`.
    -   The crucial part is the `conditions` block. It checks if the `tenant_id` from the user's session (`.Subject.tenant_id`) is equal to the tenant ID extracted from the resource URN (`.Resource.Name`).
    -   If a user from "tenant-a" tries to read `urn:myapp:products:tenant-a`, the condition passes. If they try to read `urn:myapp:products:tenant-b`, it fails.

___

#### **4\. Upstream Service: Using the `X-Tenant-Id` Header**

Finally, your main application (the upstream service) receives the request from Oathkeeper. It can now trust the headers and use them to scope its database queries.

## Update

I saw a similar discussion at Issue #2403.
