### ISSUE TITLE
Inconsistent Password Policy Validation Across Self-Service and Admin Identity API

### ISSUE THREAD

**Issue by arieltorti** [ory/kratos#3199]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When using self-service registration endpoints, the password policy validation fails for passwords like "12345678". The following error message is received:

> The password can not be used because the password has been found in data breaches and must no longer be used.

The same error message is received when using insecure passwords in the self-service settings flow:

```
 {
    "id": 4000005,
    "text": "The password can not be used because the password has been found in data breaches and must no longer be used.",
    "type": "error",
    "context": {
        "reason": "the password has been found in data breaches and must no longer be used"
    }
}
```

However, when updating passwords via the Admin Identity API, passwords are not validated. For example, "123" can be set as an identity password. In my opinion password policies should be applied everywhere to make it impossible to set a password that doesn't match the configured policies, even on admin endpoints.

### Reproducing the bug

1. Create an identity
2. Try to set its password to "123" via the [admin update identity endpoint](https://www.ory.sh/docs/kratos/reference/api#tag/identity/operation/updateIdentity)

## Expected output

Kratos should return an error saying either "123" is too short or it has been detected in breaches

## Actual output

The password is set without errors.

### Version

v0.11.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

None

**Comment by MichaelMarner** [comment]
This kind of change could affect flows such as importing users to Kratos from other IdPs, where the legacy system had different rules to Kratos.

For example, It would not be possible to bulk import users with [cleartext passwords](https://www.ory.sh/docs/kratos/manage-identities/import-user-accounts-identities#clear-text-password), because the Admin API would reject some passwords.

It would also not be possible for the admin API to enforce this consistently, for example importing hashed passwords. The admin API allows you to import identities along with their hashed passwords. As the password being imported is already hashed, Kratos can't know if the password meets the requirements.

I'm sure there could be other reasons for setting passwords that do not meet requirements. Import is just at the front of my mind because we're undertaking a move to Kratos and are going to need to import 30,000 identities. If Kratos didn't allow this flow in the Admin API it makes it difficult to move from a different IdP.

I guess what I'm saying here is that this maybe isn't a bug, but if it were to be enforced it would at the very least need to be enabled as a config option.

**Comment by aeneasr** [comment]
Thanks @MichaelMarner that is indeed intentional because of the importing use case and we don't plan on changing this, even though it is a good idea in general to validate passwords always.

By the way, bulk import is coming soon!

**Comment by fy0** [comment]
Could i disable this now?
