### ISSUE TITLE
Request for code strategy as MFA method

### ISSUE THREAD

**Issue by yojake42** [ory/kratos#3494]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When making an MFA request at ```/self-service/login``` , it will return 404 if the method is set to ```code```, with the error message ```This endpoint was disabled by system administrator. Please check your url or contact the system administrator to enable it.``` 

When looking at the API docs [here](https://www.ory.sh/docs/reference/api#tag/frontend/operation/updateLoginFlow), 'code' is the option selected in the default sample provided, and is by far the simplest and most desired case. Just send an email with a code. There's even settings to adjust the email template for this. After many many hours, I've found absolutely no information as to why this is disabled or how to enable this. I've enabled the other MFA methods in my project settings and those seem to work fine.

I can even see when exporting the config of the project:
```
selfservice:
  methods:
    code:
      config:
        lifespan: 15m0s
      enabled: true
      passwordless_enabled: false
```

Is this locked behind a paid account, accessible only in self hosted instances, or any other reason why the most basic case is disabled?

### Reproducing the bug

Make any project in the Ory Playground and attempt to make REST calls or SDK calls to login with MFA.
1. Make project
2. Create a login flow, default parameters
3. Login with email/password to get an active session
4. Create new aal2 login flow ```createNativeLoginFlow({refresh: true, aal: 'aal2', xSessionToken: mysession.data.session_token, returnSessionTokenExchangeCode: true}```
5. Attempt to invoke the 'code' MFA flow ```updateLoginFlow({flow: flow.id, xSessionToken: mysession.data.session_token, updateLoginFlowBody: {method: 'totp'}})```

### Version

1.2.5

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Ory Network

**Comment by vinckr** [comment]
> Is this locked behind a paid account, accessible only in self hosted instances, or any other reason why the most basic case is disabled?

Definitely not! 

I tried this out on my Demo project and it worked without issues - I did not use the mobile SDK though, maybe it is related to that 🤔 
Would have to do another session to check that out.

Are you using the latest [ory-client](https://www.npmjs.com/package/@ory/client) SDK?

**Comment by aeneasr** [comment]
The code method does currently not support MFA. It's a first-factor only.

**Comment by Sytten** [comment]
I want to pitch in:

We are currently implementing social logins in our application. I was revisiting https://github.com/ory/kratos/issues/2586 since this becomes a real issue. The suggested solution is to force the aal to be `strict` (which I don't think is a valid value anymore), basically forcing it to be aal2. Right now that means forcing the user to setup TOPT, lookup secrets or webauthn. But it is not possible to setup those before having a privileged session. There is a chicken and egg problem.

I am proposing that we allow the one-time code method to be used as MFA. This would allow us to require aal2 on settings update (`required_aal`) for all users even if they didn't setup other MFA methods (like if they came from a social login).

**Comment by aeneasr** [comment]
That's true, Vincent was probably referring to `highest_available` AAL setting. In my view, OTP codes send to emails or phones are not MFA and the NIST for example agrees in their digital identity guidelines. Generally speaking, I would like to avoid email OTP as a second factor:

> Email is not true MFA because it does not represent a different factor than the password. It does not represent something I have or something I am, but rather just something I know (the email password). It is also weaker than other factors in that it's only as secure as the email itself (for example, encrypted end-to-end).

In my view, this also doesn't really address #2586 which is a different problem in my view (re-confirming the password when changing it).

**Comment by Sytten** [comment]
My point really is that even with a solution for https://github.com/ory/kratos/issues/2586, if you steal a cookie from the user within the first minutes of the session it is basically game over because you can freely change the settings including which social accounts are linked and the password. This is because the user gets a `sudo` mode automatically on login, the MFA usually prevents that. Email is not perfect, but it is preferable to nothing IMO (at least for this particular attack).

I agree that if another MFA is set it should be used, so maybe kratos needs more `AAL` categories. There is also the case where usually on social logins you don't want to set another MFA on top of it.

It is a hard problem, but I feel kratos doesn't help much to deal correctly with websites that enable both Social and Password logins.

**Comment by Sytten** [comment]
Agreed, I guess the more I think about it the more I feel like it probably is best to let the user change the settings but inform him via email / have an audit trail of the changes.

True, I still like the fact that the `sudo` session is separated in Github (I think it is even another cookie) and you don't have to re-login to access it. In kratos that would translate to another flow where you can configure what you want for it and different webhooks than for login. Food for thought...

**Comment by aeneasr** [comment]
We have shipped several improvements. It is now significantly improved, and the code strategy can now be used for MFA.
