### ISSUE TITLE
Add recovery url with flow id to password code recovery

### ISSUE THREAD

**Issue by reginbald** [ory/kratos#3619]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

I'd like the email to include a link to the recovery page where the user can insert the recovery code.
https://example.com/ui/recovery?flow=<flow-guid>

### Describe your ideal solution

RecoveryCodeValidModel would include a new property called url that would have the recovery url and flow id

### Workarounds or alternatives

Not including the url

### Version

oryd/kratos:v1.0.0

**Comment by reginbald** [comment]
Are there maybe some security concerns that I am not aware of?

**Comment by jonas-jonas** [comment]
> Are there maybe some security concerns that I am not aware of?

Yes. This was left out on purpose, because the flow is protected by anti-CSRF measures. Including a link to the form would work if the user always uses the same browser. But depending on the user's device settings, the link might open in a different browser than the one they used to create the code. Opening the link would then just show an error message (because the CSRF cookie is missing). This is bad UX, so we opted to not even make this possible.

**Comment by reginbald** [comment]
I understand. Thanks for clearing this up for me
