### ISSUE TITLE
Dynamic Multitenant setup support

### ISSUE THREAD

**Issue by Nekuromento** [ory/kratos#407]
**Is your feature request related to a problem? Please describe.**

At this moment Kratos is designed to provide login/registration flow for one tenant. Official documentation suggests deploying multiple Kratos instances for multi-tenant solutions.
The proposed solution is challenging to implement for dynamically created tenants as it requires deploying and managing new Kratos instances.

**Describe the solution you'd like**

- Have a way to have more then one user pool in Kratos
- A way to specify which user pool will be used in the user login/registration flow so that only users from that pool could login/register
- Allow dynamic redirect configuration

**Comment by aeneasr** [comment]
Sorry, this is a non-goal for ORY Kratos. Multi-tenancy must be solved by deploying multiple instances, otherwise complexity will explode. It's better for security (isolation), scaling (sharding) and systems like Kubernetes are an acceptable trade-off for doing this. Implementing multi-tenancy on an application level is very hard and explodes in complexity quickly.

**Comment by aeneasr** [comment]
I believe the question has been answered appropriately -> closing
