### ISSUE TITLE
Can`t install on Mac by brew , Msg: The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by panda8z** [ory/kratos#423]
**Describe the bug**

```bash
$ brew install ory/kratos/kratos
Updating Homebrew...
==> Installing kratos from ory/kratos
==> Downloading https://github.com/ory/kratos/releases/download/v0.3.0-alpha.1/k

#=#=-#  #                                                                     
curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "kratos"
Download failed: https://github.com/ory/kratos/releases/download/v0.3.0-alpha.1/kratos_0.3.0-alpha.1_macos_amd64.tar.gz

```
**Reproducing the bug**

1. follow the MacOS installition guide:[Installation | ORY Kratos](https://www.ory.sh/kratos/docs/install)

**Environment**

- Version: MacOS 10.15.4
- Environment: MacOS, zsh

**Comment by zepatrik** [comment]
As @tricky42 and @tacurran investigated today the URL in kratos' homebrew repo is wrong.
It should be `...macos_64bit.tar.gz` instead of `macos_amd64.tar.gz`.

**Comment by aeneasr** [comment]
Yeah looks like the replacements are misconfigured in our goreleaser file.

**Comment by eriklott** [comment]
The `brew install ory/kratos/kratos` command still seems to be returning error ` The requested URL returned error: 404 Not Found` on macos.

**Comment by tacurran** [comment]
@eriklott I thought we fixed that. But its still not working?  This is the fix for brew: https://github.com/ory/kratos/commit/fd269b1afa784becac7ee79cd7a6f9d2bbe39121
Most likely this is a problem with gorelease automation.

**Comment by tacurran** [comment]
@eriklott I just checked into this yesterday. This issue #423 is closed since its fixed in the next release already. 
https://github.com/ory/kratos/commit/fd269b1afa784becac7ee79cd7a6f9d2bbe39121

As a workaround:
1.  Go to  https://github.com/ory/kratos/releases/tag/v0.3.0-alpha.1
2. Scroll down to the 'Assets' section
3. Click on the version you need e.g. kratos_0.3.0-alpha.1_macos_64bit.tar.gz
4. Download into your local machine. 
5. type  kratos help
