### ISSUE TITLE
Support for non-SQL backends

### ISSUE THREAD

**Issue by m13t** [ory/kratos#660]
**Is your feature request related to a problem? Please describe.**

Really like the software that’s being built, but it would be nice if the database abstraction supported more than just SQL via Pop. It would be great if the was a more friendly interface so that we can easier write backends for things like DynamoDB or MongoDB for example.

**Describe the solution you'd like**

To be able to possibly write plugins for the DBA layer that conform to a generic interface for communicating with a data store. This way the community can drive the databases supported by the application and better integrate with their existing stack.

**Describe alternatives you've considered**

None so far.

**Additional context**

N/A

**Comment by NurdinDev** [comment]
Interesting discussion, I reach this thread because I'm searching if there is a way to use Kratos with Mongo, and it seems not, but I'm curious to know what is the side effects if I used both databases? 
(Postgress for ORY) and (Mongo for my Database) and I'll store the userID also in my database like if I'm used Auth0, all the users are stored in their database. 

Appreciate any feedback whether if it's a good or a bad approach to use ORY services in this way.

**Comment by aeneasr** [comment]
It's a perfectly fine approach! The userID in Ory Kratos is stable (never changes)

**Comment by forresthopkinsa** [comment]
Just to give my 2¢: NoSQL databases like DynamoDB make _way_ more sense for serverless applications, at least due to their pricing model. A small project can't afford to keep a relational DB instance constantly running.

**Comment by forresthopkinsa** [comment]
SQLite is not a terrible recommendation for a small project. It does, however, impose some serious scaling limitations.

Say you're running an application completely in Lambdas using Dynamo. You inherit practically infinite scalability (assuming perfect code), while also costing *nothing* until you reach a high amount of adoption:

- Lambda gives 1M free requests and 3.2M free seconds of compute per month
- Dynamo gives 25 GB free storage and 200M free requests per month

The most Lambda-friendly relational DB would be Aurora Serverless, but that can't practically scale to zero due to _really_ long cold starts. That pretty much just leaves Dynamo.

I completely sympathize with your argument about vendor lock-in and the required effort. I don't have any counterargument for those things. I understand this isn't going to happen any time soon. I just want to put it out there that the locked-in option is _very_ attractive, cost-wise, for small but scalable projects, and in my case it disqualifies Kratos despite how much I like it.
