### ISSUE TITLE
Implement React SPA sample app

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos#668]
A React SPA application using ORY Kratos with tutorial.

- [ ] Publish tutorial on the website and link it in the docs
- [ ] Log in with password / oidc
- [ ] Sign up with password / oidc
- [ ] Update settings
- [ ] Re-request verification mail
- [ ] Logout
- [ ] Request account recovery

**Comment by gperdomor** [comment]
@aeneasr any progress here?

**Comment by wilcoschoneveld** [comment]
@aeneasr I'm working on implementing an SPA and I have a question about retrieving a request id for a flow.

In the login screen, I can check for the request id in the query parameters and, if it's not available, navigate to kratos self-service which will redirect me back. This seems to be the intended usage but it requires a reload of the application.

I've experimented with using an iframe for retrieving a request id and using [postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to send this id to the SPA. It does require a backend which can give some javascript to facilitate this `postMessage()` call and which is configured as the Kratos return url, but it seems to work fine!

What do you think? Is it viable to connect an SPA to Kratos without redirecting/reloading, or is this not desired (e.g. security reasons)?

**Comment by aeneasr** [comment]
No, redirection is required to set up the cookies for CSRF prevention!

**Comment by wilcoschoneveld** [comment]
I did a little proof of concept in React here: https://github.com/wilcoschoneveld/kratos-selfservice-ui-react

1. clone the repo
2. run `docker-compose up`
3. run `yarn install` and `yarn start`
4. navigate to http://127.0.0.1:3000/auth/login

it will fetch a request id via a redirect in a hidden iframe, and it will render something like:
`Request: d579b9c7-a980-48c4-9823-4170fcf59332`

the hidden iframe redirect also sets the CSRF cookie.

**Comment by Serhii-the-Dev** [comment]
@aeneasr could you please describe your vision of Kratos integration in case of SPA? We have a case when some actions requiring user authentication via pop-up **without app reload**, which is one of the main concepts of SPAs. We could re-use all components we have in the app within this pop-up(input fields, buttons, form error handling logic) without making a duplicating web-site.  With CORS enabled we could be sure that only a domain hosting the SPA could be an originator of auth requests. Isn't this enough?

**Comment by aeneasr** [comment]
It is currently not possible to log in without a reload! The first redirect is required to establish the appropriate cookie.

**Comment by Serhii-the-Dev** [comment]
@aeneasr thank you, it's totally understandable, I've implemented a kind of integration with help of Next.js and forwarding of the cookies along with form data...alas, it's still SSR, which could be fine in certain scenarios(i.e. a separate login page), but not allowing to deploy the app as a static content on cloud hosting. I'm trying to understand if there are plans to support SPAs that integrates authentication form into their UI without refreshing the entire app. Unfortunately, I'm not very experienced in web security so want to know your opinion on the topic: would it be sufficient to use CORS + API approach instead of redirects? Up to my understanding the most obvious attack vector in this case would be a possibility of XSS on CORS-allowed domain only.
For example, when using the AWS Cognito along with Amplify [we could authenticate a user](https://docs.amplify.aws/lib/auth/emailpassword/q/platform/js) through XHR/fetch without refreshing of the page.
Currently I'm seeing a lot of warnings in Kratos documentation that disallowing such an approach, and we followed this practice so far, however I'm curious if there is a way to keep that level of simplicity we had with home-made auth system.

**Comment by Serhii-the-Dev** [comment]
I will answer the question regarding SOP and CORS by myself: no, it's not enough. SOP will block other origins from **reading** of response data from your domain. However, a request and all the logic behind it will be processed by a server. There are some scenarios when browser **should** send a preflight request before POST, however, it's not guaranteed even in modern browsers and rules are tricky. Taking into account that **client** decides if this policy should be checked, it shouldn't be used for server-side security by any means(i.e. "never trust the client side").
There is another option that allows to not stick with cookies and tokens for CSRF protection: to check if `Origin` or `Referer` header strictly matches allowed domains:
```regex
/^https:\/\/(example.com|example2.com)/g
```
Unfortunately, in this case we may loose the clients that have some proxies stripping out non-standard headers. Also some browsers may not send those headers at some circumstances.
Definitely should to checks how it's implemented in AWS Amplify...

**Comment by aeneasr** [comment]
Yes, it's very difficult to implement cookie behavior correctly without redirecting the browser itself as there are many potential security rules that are also constantly being changed (e.g. SameSite, httpOnly, secure, ...), making this much harder. I haven't used AWS Cognito in a while but whenever I did it felt like a huge hack job to me where 80% worked fine and 20% were simply impossible to implement or had horrendous workarounds.

I think, at some point, we can support SPA without reloading if everything runs on the same domain but for the time being it is unfortunately not possible. I think reloading the page is a small trade off you make for a hardened, secured identity server. Most other services require you to even leave your domain (e.g. Auth0, Okta) in order to perform their OAuth2 flow, completely breaking user experience. ORY Kratos has a good trade off in my opinion, but we'll try to improve it - it's just not very high on the prio list at the moment!

**Comment by aeneasr** [comment]
Pushing this back into 0.6!

**Comment by borchero** [comment]
I've been experimenting with Kratos in a Vue SPA and it was actually quite straightforward to make the registration flow work without any page reloads (and without any iframes).

Basically, I'm using navigation guards of Vue router to ensure that, whenever the registration URL is accessed at `/auth/register`, a registration flow is initiated via AJAX and the returned flow ID is appended to `/auth/register`. To make this work, I'm setting the `Accept: text/html` header (which is a little "hacky" but at least it works).

Since I only started to get accustomed with coding for the browser like a week ago, I'm now wondering if my approach opens any attack vectors? I noticed that a `csrf_token` cookie is set on the first AJAX call to `/self-service/registration/browser` (with or without `{credentials: true}` being set in the corresponding axios call). However, its value does not change on subsequent visits. Also, there is not `Set-Cookie` header anymore -- I'm wondering if this is intended behavior since I observe the same behavior when using the reference UI for Kratos.

In any case, I fail to understand the usefulness of this `csrf_token` cookie. Evidently, it's not checked against the CSRF token sent via the form since submitting the form also works with a "stale" value of `csrf_token`.

I would appreciate any insights ;)

**Comment by aeneasr** [comment]
Welcome to the Ory family @borchero . Please note that this thread is to track the React SPA example app feature for Ory Kratos. If you have questions on how to implement your app, please head over to github discussions or on slack, thanks!

**Comment by saltbo** [comment]
I have the same question, is there a problem with CSRF attacks in implementing SPA applications?

**Comment by grantzvolsky** [comment]
CSRF is not a concern if your servers exclusively authorize requests using headers that aren't automatically appended to requests by the browser, e.g. the Authorization header. I can think of two disadvantages of this approach.
1. If someone gets XSS access to your client, they can steal tokens from localStorage and use them offline rather than just while the client is online. Whether this is a problem depends on the use case.
2. It doesn't work without using the localStorage browser API. Tokens in the URI are not an option.

That being said, I haven't seen any major project implement a cookieless flow so I wouldn't expect the Ory React SPA sample app to be the first one.

**Comment by sbussard** [comment]
I'd like to reference this comment here since there are several issues around SPAs
https://github.com/ory/kratos/issues/1138#issuecomment-846654658

**Comment by aeneasr** [comment]
Once https://github.com/ory/kratos/pull/1367 lands this will become easier / work with AJAX :) Already have a NextJS example against that branch that works incredibly well and is really easy to use!

**Comment by ramsy1980** [comment]
I've made a NextJS version with basic functionality. 

https://gitlab.com/commondatafactory/cdf-identity-platform/self-service-node

**Comment by lanphan** [comment]
@ramsy1980 
Thanks so much for your source code. I did try your example with latest version from ory kratos, v0.7.1-alpha.1-sqlite, it's ok to display login flow id and all api works, but html raises issues. Would you please help to check again and update your source code? I'm not good at frontend side.

**Comment by ramsy1980** [comment]
> @ramsy1980
> Thanks so much for your source code. I did try your example with latest version from ory kratos, v0.7.1-alpha.1-sqlite, it's ok to display login flow id and all api works, but html raises issues. Would you please help to check again and update your source code? I'm not good at frontend side.

Can you raise a bug on the repo with some additional info? And I'll pick it up.

**Comment by lanphan** [comment]
Hi @ramsy1980 ,
I raised bug https://gitlab.com/commondatafactory/cdf-identity-platform/self-service-node/-/issues/3 here, please help to take a look, thanks.
