### ISSUE TITLE
[K8 Helm] Errors upon install

### ISSUE THREAD

**Issue by DarkBlaez** [ory/kratos#699]
Per the install using this link:  https://k8s.ory.sh/helm/kratos.html

DSN is set, Secret/Session is set

Resulting Error:
identity: <nil>
2020-09-21T16:49:52.192439865Z           ^-- one or more required properties are missing
2020-09-21T16:49:52.192444892Z 
2020-09-21T16:49:52.192454407Z courier.smtp.connection_uri: <nil>
2020-09-21T16:49:52.192457867Z                              ^-- one or more required properties are missing
2020-09-21T16:49:52.192461628Z 

The referenced entities are not referenced in the values.yaml. Are the instructions up to date for this version (v0.4.2)

Please advise

Thanks
DB

**Comment by DarkBlaez** [comment]
Based on review of the helm chart it seems as is always the case the focus is on docker-on-host and Kratos cli. The helm chart seems to be lacking an operational install based on the instructions. This seems like yet another out-of-date set of documents.

Please either update the K8 documents or remove them. It does a disservice when most will start to install on Kubernetes. Granted one can write manifest around the docker container which most likely address much of the gap with the stale helm charts. However, too much is left for digging and to be inferred.

DB

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.
