### ISSUE TITLE
Add return_to after logout

### ISSUE THREAD

**Issue by aikoven** [ory/kratos#702]
**Describe the bug**

When there's already a session, we can force the login page using `refresh=true`. But if a user goes to registration, they get immediately redirected to the default return url. 

**Reproducing the bug**

1. Complete login flow to get a session.
2. Start login flow once again with refresh=true, see the login form.
3. Attempt to start registration flow and get redirected to default return url instead of seeing the registration form.

**Expected behavior**

I expected to be able to go to registration from the login page, or at least be able to pass `refresh=true` to the registration flow.

**Environment**

- Version: v0.4.6
- Environment: Docker

**Comment by zepatrik** [comment]
I see your point, but is this really a flow your users will do? We always compare this to GitHubs sudo mode. It only asks for the user's password because she is logged in already. If you want your users to be able to switch accounts at that point it would make more sense to offer a logout option and display their name/avatar/... to indicate that they are logged in still.

**Comment by aikoven** [comment]
Thank you for clarification, this makes a lot of sense!

**Comment by aikoven** [comment]
Following your advice, I'm showing current logged-in identity and a `Switch account` link pointing to Kratos logout flow. But I can't figure out how to continue the parent flow after that. It seems that Kratos logout flow does not recognize `return_to` query parameter.

**Comment by zepatrik** [comment]
Right, looks like it is not implemented yet.
