### ISSUE TITLE
selfservice/flow/settings/handler.go:60:3: duplicate method CSRFHandler

### ISSUE THREAD

**Issue by koma136** [ory/kratos#789]
**Describe the bug**

**Reproducing the bug**

_Server logs_

_Server configuration_

**Expected behavior**

**Environment**

- Version: v1.2.3, git sha hash
- Environment: Debian, Docker, ...

**Additional context**

**Comment by aeneasr** [comment]
Thank you for contributing to this repository by creating an issue!

Unfortunately, your issue lacks vital information, such as log files, the error message, the software version, your configuration or other pieces of the puzzle.

Please also ensure that your issue is appropriately formatted. If you do not know how to write markdown, you can find help [here](https://guides.github.com/features/mastering-markdown/).

Helping you with your problem is only possible if you share this information, and it will save a lot of time of back and forth on your as well as our end!

For this reason, this repository uses [issue templates](../tree/master/.github/ISSUE_TEMPLATE) which you can select when pressing "New issue". Please use one of those issue templates to fill in the required information. You can either create a new issue for this purpose and close this one, or leave a comment. 

> Do not edit the original post as we will not be notified when you do so.

If you do not provide the requested information, this issue will be closed.

**Comment by koma136** [comment]
run go1.13
