### ISSUE TITLE
Documentation: JSON Schema Vocabulary / Schema Updates

### ISSUE THREAD

**Issue by Alisaien** [ory/kratos#864]
**Problem**
1. Currently the only location where it is documented, that
```json
"recovery": {
  "via": "email"
}
```
is needed for email recovery flow, is at https://www.ory.sh/kratos/docs/self-service/flows/account-recovery/#recovery-link-method
This page is for "self-service", so it is really hard to find.

2. Kratos behaviour on schema updates for existing users (for example if updates are incompatible like new required properties)

**Solution**
1 . Add documentation of the vocabulary extension to "Concepts/Identity Data Model" or "Reference/JSON Schema and JSON Paths"
(By the way I expected the documentation for the schema expected by Kratos at "Reference/JSON Schema and JSON Paths" not just links)

2. Should also be documented at "Concepts/Identity Data Model" or "Reference/JSON Schema and JSON Paths"

**Note**
I am willing to update the docs once we have decided on a location, etc.

**Comment by vinckr** [comment]
Is it hard to find because the term "self-service" is not clear here? 
Yu would look for end-user capabilities and then see "account recovery" and find the recovery schema, right?

Identity data model is more about general concepts than about specific code you need for user capabilities. 

I agree that the "Reference/JSON Schema and JSON Paths" is not totally what you would expect, I would expect a reference JSON schema as well, and not an explanation of what JSON is. 

Imho it would be good to add some reference schema to "Reference/JSON Schema and JSON Paths".
This stuff is not really fitting into "Concepts/Identity Data Model", but that is just my opinion.

The important goal is here to help everyone find the information they are looking for in the documentation! 

Lets wait for the maintainers give their opinion here, before we start restructuring ;).

**Comment by Alisaien** [comment]
I was experimenting with a minimal default schema and tried to "invite" a user following the guide at "Administration/Managing Users and Identities" and because recovery was not documented under "Concepts/Identity Data Model" I did not have in my schema. Since it concerns admin as well as self-service I think listing it exclusively under self-servicing is confusing/hard to find.
After that I updated the schema and restarted Kratos but, because the recovery addresses were not updated, I deleted the test users and added them again and then I worked. This is led to the second point, which is especially important for the default schema. Maybe the default schema should only be a pointer to an explicitly declared schema, this would make versioning behavior clearer.

**Comment by aeneasr** [comment]
So I think we should just add that section about the schema to this document as well: https://www.ory.sh/kratos/docs/admin/managing-users-identities#invite-a-user

@vinckr could you do that?

**Comment by vinckr** [comment]
I made some changes: https://github.com/ory/kratos/pull/868
You think that makes it more clear @Alisaien?
In any case thanks for pointing this out!

**Comment by Alisaien** [comment]
I think this helps, but ultimately I think it is best to make a reference page just like the config file -- especially if the number of options grows in the future.
And as I already said, it would be good to document how Kratos behaves when schemas are updated.

As an aside:
1. I think the client api is currently (v0.5.4-alpha.1) broken.  From I understand from looking through community/issues you did a deduplication from `/self-service/api/...` and `/self-service/browser` to `/self-service/.../api|browser` but because of this the CSRF middleware blocks api client POST requests. This should be easy to test with any image. (Maybe the error is on my side, but from my tests this seems to the problem)
2. Have you considered using custom http headers instead of cookie double submit, because imo using custom headers would make things easer. If you are open to discussing this I will start a thread.
