### ISSUE TITLE
Recovery self service flow does not pass on redirect_to URL

### ISSUE THREAD

**Issue by zepatrik** [ory/kratos#914]
The recovery flow should pass on the `return_to` or `...recovery.after.default_browser_return_url` to the following settings flow. This way the user ends up at the correct page after it completed all steps required for recovery.

Start here: https://github.com/ory/kratos/blob/48078e9a3f9734b64d587a43fe436d4c3e78120b/selfservice/strategy/link/strategy_recovery.go#L456

**Comment by Beetix** [comment]
Seems like the redirect happens here:
https://github.com/ory/kratos/blob/48078e9a3f9734b64d587a43fe436d4c3e78120b/selfservice/strategy/link/strategy_recovery.go#L344

**Comment by Beetix** [comment]
I took some time to study the code.

When the recovery flow is completed, a new settings flow is created and the user is redirected the settings UI with a flow token:
https://github.com/ory/kratos/blob/48078e9a3f9734b64d587a43fe436d4c3e78120b/selfservice/strategy/link/strategy_recovery.go#L332-L344

This is sensible since the user is bound to change his password. Unfortunately, this is currently not compatible with the return URL mechanism.

I see 2 options:

- Not creating a settings flow if a return URL is specified
- Calling the return URL with the settings flow token

The later seems more relevant since as mentioned before the user is bound to change his password.

What's your take on this?

**Comment by aeneasr** [comment]
Thank you for thinking about this @Beetix ! I don't think the second option is valid, it can easily be abused by an attacker to present you a phony "update your password ;) ;)" UI which is actually a phishing site. What we could do though is calling the return_to URL once the settings flow was completed!

**Comment by Beetix** [comment]
> Thank you for thinking about this @Beetix ! I don't think the second option is valid, it can easily be abused by an attacker to present you a phony "update your password ;) ;)" UI which is actually a phishing site. What we could do though is calling the return_to URL once the settings flow was completed!

Yes, calling the return_to URL after the settings flow seems better. I have proposed these ideas while trying to figure out a way to focus the user on changing his password. The issue with the settings flow is that a user can update his profile instead of his password (which is what really matters in a recovery).

**Comment by zepatrik** [comment]
If you want to prevent that you can omit the other fields in the UI. It will probably change with #929 so that traits and password are separated anyway.

**Comment by Beetix** [comment]
> If you want to prevent that you can omit the other fields in the UI. It will probably change with #929 so that traits and password are separated anyway.

Yes, resolving #929 seems to be the answer to my problem. Having a single URL for both is problematic. If I hide the fields in the UI it means that I'll never be able to change these settings.

**Comment by zepatrik** [comment]
You can hide them conditionally, depending on the referrer or some query parameter.
