### ISSUE TITLE
Typescript Formfield.value type is incorrect

### ISSUE THREAD

**Issue by TMInnovations** [ory/kratos#916]
**Describe the bug**

The current typescript type for Formfield.value in api.d.ts doesn't correctly represent the payload.

**Reproducing the bug**

Look at the typescript bindings to see the Formfield.value type.

```
export interface FormField {
     ...
     * Value is the equivalent of `<input value=\"{{.Value}}\">`
     * @type {object}
     * @memberof FormField
     */
     value?: object;
}
```
Call getSelfServiceRegistrationFlow from the typescript sdk and look at the response, that is a string.
```
e.data?.methods['password']?.config?.fields[<a field with string as value>].value
```

If object is needed, a type value?: object|string; would be sufficient.

**Environment**
-v client: @oryd/kratos-client: ^0.5.4-alpha.1
-v server: oryd/kratos:v0.5.4

**Comment by vinckr** [comment]
For other readers reference sdk code lives in the [ory/sdk repository](https://github.com/ory/sdk).
You are referring to [api.ts ](https://github.com/ory/sdk/blob/90f86eb14e123801663091c6c8318ef51bbac8cc/clients/kratos/typescript/api.ts#L166)

We generate all SDKs with openapi-generator, so this stems from there I think. 

You would expect `value?: object|string;` instead of `value?: object;` is that correct?

**Comment by aeneasr** [comment]
I think `object|string` could work but `number|string` would probably be correct. The problem really is that the type is inferred by `interface{}` which go-swagger translates to `object`. I don't have an easy fix for this at the moment but feel free to investigate and propose alternatives.

What we really would need is for us to force a swagger type on a field in go-swagger using e.g. `type: string`. The problem here again is that `string|number` would mean `oneOf` which is even harder to set...

**Comment by aeneasr** [comment]
Resolved on master
